import { Fragment } from "react";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import IntroductionVideo from "../components/Introductionvideo";
import HolonStyle from "./holon-style";
import TextBlock from "../components/textBlock";

import ContentBlock from "../components/ContentBlock";

function Card({ children, href }) {
  return (
    <a
      href={href}
      className="align-left m-3 max-w-xs rounded-md border p-5 text-black no-underline transition"
    >
      {children}
    </a>
  );
}

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="snap-y snap-mandatory h-screen overflow-y-auto">
      <ContentBlock colorClass="bg-split-white-blue">
      </ContentBlock>
      <ContentBlock colorClass="bg-holon-blue-900" id="introVideo">
      <IntroductionVideo />
      </ContentBlock>
      <ContentBlock colorClass="bg-split-blue-white">
      </ContentBlock>
      <ContentBlock>
        <TextBlock  value="hoeDoen" borderColor="holon-slated-blue-300"> 
        </TextBlock>
      </ContentBlock>
      <ContentBlock>
        <TextBlock value="slimmerSamenwerken" borderColor="holon-gold-200" right="true"> 
        </TextBlock>
      </ContentBlock>
      <ContentBlock>
        <TextBlock value="warmte" borderColor="holon-blue-900"> 
        </TextBlock>
      </ContentBlock>
      <ContentBlock>
        <TextBlock value="tweeKeerSlimmer" borderColor="holon-grey-300" right="true"> 
        </TextBlock>
      </ContentBlock>
      <ContentBlock colorClass="bg-split-white-blue">
      </ContentBlock>
      
      <ContentBlock colorClass="bg-cyan-400" id="blue" linkname="#purple">
      <p className="text-lg">Er is hier een voorbeeldtekst met een 
    <Link href="#introVideo"> link
    </Link></p>
      </ContentBlock>   
      </main>
      

      
    </div>
  );
}
