# Generated by Django 4.1.2 on 2022-10-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customdocument", "0003_auto_20190209_1710"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("timestep_hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("force_uncached", models.BooleanField()),
                ("show_progress", models.BooleanField()),
                ("parallelize", models.BooleanField()),
                ("log_exceptions", models.BooleanField()),
                (
                    "config_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="customdocument.customdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario tags",
            },
        ),
    ]
