# Generated by Django 4.1.7 on 2023-03-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="GridConnection"),
        migrations.DeleteModel(name="Factor"),
    ]
