# Generated by Django 4.1.7 on 2023-03-13 12:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceGroupModelOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "asset_to_balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.energyasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "BalanceGroupModelOrder",
            },
        ),
        migrations.RenameField(
            model_name="ruleactionadd",
            old_name="asset",
            new_name="asset_to_add",
        ),
        migrations.RenameField(
            model_name="ruleactionadd",
            old_name="contract",
            new_name="contract_to_add",
        ),
        migrations.RenameField(
            model_name="ruleactionadd",
            old_name="gridconnection",
            new_name="gridconnection_to_add",
        ),
        migrations.RenameField(
            model_name="ruleactionbalancegroup",
            old_name="selected_asset_type",
            new_name="selected_model_type_name",
        ),
        migrations.RenameField(
            model_name="ruleactionsetcount",
            old_name="asset",
            new_name="asset_to_add",
        ),
        migrations.RenameField(
            model_name="ruleactionsetcount",
            old_name="contract",
            new_name="contract_to_add",
        ),
        migrations.RenameField(
            model_name="ruleactionsetcount",
            old_name="gridconnection",
            new_name="gridconnection_to_add",
        ),
        migrations.AlterField(
            model_name="ruleactionadd",
            name="rule",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discrete_factors_add",
                to="holon.scenariorule",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionsetcount",
            name="rule",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discrete_factors_set_count",
                to="holon.scenariorule",
            ),
        ),
        migrations.DeleteModel(
            name="BalanceGroupAssetOrder",
        ),
        migrations.AddField(
            model_name="balancegroupmodelorder",
            name="balance_group",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_group_model_order",
                to="holon.ruleactionbalancegroup",
            ),
        ),
        migrations.AddField(
            model_name="balancegroupmodelorder",
            name="contract_to_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.contract",
            ),
        ),
        migrations.AddField(
            model_name="balancegroupmodelorder",
            name="gridconnection_to_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
    ]
