# Generated by Django 4.1.7 on 2023-03-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contractScope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="holon.actor"
            ),
        ),
    ]
