# Generated by Django 4.1.7 on 2023-03-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_casuspage_scenario_alter_challengemodepage_storyline_and_more"),
        ("holon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelement",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National", "Level National"),
                    ("Intermediate", "Level Intermediate"),
                    ("Local", "Level Local"),
                ],
                help_text="If type is 'Continuous (slider)', choose a level. Otherwise, leave it empty",
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveelement",
            name="link_wiki_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to link to an internal wiki page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="interactiveelement",
            name="more_information",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="interactiveelement",
            name="scenario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.scenario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interactiveelementoptions",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No color", "Color None"),
                    ("Red", "Color Red"),
                    ("Orange", "Color Orange"),
                    ("Green", "Color Green"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveelementoptions",
            name="legal_limitation",
            field=models.CharField(
                blank=True,
                help_text="Fill in the status of the legal limitation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveelementoptions",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National", "Level National"),
                    ("Intermediate", "Level Intermediate"),
                    ("Local", "Level Local"),
                ],
                default="National",
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveelementoptions",
            name="link_wiki_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to link to an internal page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.wikipage",
            ),
        ),
        migrations.AlterField(
            model_name="interactiveelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("single_select", "Choice Singleselect"),
                    ("multi_select", "Choice Multiselect"),
                    ("continuous", "Choice Continuous"),
                ],
                default="continuous",
                max_length=19,
            ),
        ),
    ]
