# Generated by Django 4.1.6 on 2023-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("Asset", "AssetOld"),
        migrations.RenameModel("GridConnection", "GridConnectionOld"),
    ]
