# Generated by Django 4.1.6 on 2023-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("holon", "0002_auto_20230203_1459"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GRIDOPERATOR", "Gridoperator"),
                            ("ADMINISTRATIVEHOLON", "Administrativeholon"),
                            ("ENERGYHOLON", "Energyholon"),
                            ("CONNECTIONOWNER", "Connectionowner"),
                            ("ENERGYSUPPLIER", "Energysupplier"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("commercial", "Commercial")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "parent_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.actor",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EnergyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="GridConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity_kw", models.FloatField()),
                (
                    "charging_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAX_POWER", "Max Power"),
                            ("MAX_SPREAD", "Max Spread"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "battery_mode",
                    models.CharField(
                        blank=True,
                        choices=[("BALANCE", "Balance"), ("PRICE", "Price")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("nfATO_capacity_kw", models.FloatField(blank=True, null=True)),
                ("nfATO_starttime", models.FloatField(blank=True, null=True)),
                ("nfATO_endtime", models.FloatField(blank=True, null=True)),
                ("assets", models.ManyToManyField(blank=True, to="holon.energyasset")),
                (
                    "owner_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="holon.actor"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="GridNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity_kw", models.FloatField()),
                (
                    "owner_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="holon.actor"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.gridnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ELECTRIC_VEHICLE", "Electric Vehicle"),
                            ("STORAGE_ELECTRIC", "Storage Electric"),
                            ("STORAGE_HEAT", "Storage Heat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("stateOfCharge_r", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="factor",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="BuiltEnvironmentGridConnection",
            fields=[
                (
                    "gridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.gridconnection",
                    ),
                ),
                (
                    "insulation_label",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("NONE", "None"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "heating_type",
                    models.CharField(
                        choices=[
                            ("GASBURNER", "Gasburner"),
                            ("GASFIRED", "Gasfired"),
                            ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                            ("DISTRICTHEAT", "Districtheat"),
                            ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                            ("HYDROGENFIRED", "Hydrogenfired"),
                            ("NONE", "None"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.gridconnection",),
        ),
        migrations.CreateModel(
            name="ConsumptionAsset",
            fields=[
                (
                    "energyasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY_DEMAND", "Electricity Demand"),
                            ("HEAT_DEMAND", "Heat Demand"),
                            ("HOT_WATER_CONSUMPTION", "Hot Water Consumption"),
                            (
                                "OTHER_ELECTRICITY_CONSUMPTION",
                                "Other Electricity Consumption",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.energyasset",),
        ),
        migrations.CreateModel(
            name="ConversionAsset",
            fields=[
                (
                    "energyasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOILER", "Boiler"),
                            ("ELECTROLYSER", "Electrolyser"),
                            ("GAS_BURNER", "Gas Burner"),
                            ("HEAT_DELIVERY_SET", "Heat Delivery Set"),
                            ("HEAT_PUMP_AIR", "Heat Pump Air"),
                            ("HEAT_PUMP_GROUND", "Heat Pump Ground"),
                            ("HYDROGEN_FURNACE", "Hydrogen Furnace"),
                            ("METHANE_FURNACE", "Methane Furnace"),
                            ("DIESEL_VEHICLE", "Diesel Vehicle"),
                        ],
                        max_length=255,
                    ),
                ),
                ("eta_r", models.FloatField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.energyasset",),
        ),
        migrations.CreateModel(
            name="ElectricGridNode",
            fields=[
                (
                    "gridnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.gridnode",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("MSLS", "Msls"), ("HSMS", "Hsms")], max_length=4
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.gridnode",),
        ),
        migrations.CreateModel(
            name="ElectricStorageAsset",
            fields=[
                (
                    "storageasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.storageasset",
                    ),
                ),
                ("capacityElectricity_kW", models.FloatField()),
                ("storageCapacity_kWh", models.FloatField()),
            ],
            bases=("holon.storageasset",),
        ),
        migrations.CreateModel(
            name="HeatGridNode",
            fields=[
                (
                    "gridnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.gridnode",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("MT", "Mt"), ("HT", "Ht")], max_length=2
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.gridnode",),
        ),
        migrations.CreateModel(
            name="HeatStorageAsset",
            fields=[
                (
                    "storageasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.storageasset",
                    ),
                ),
                ("capacityHeat_kW", models.FloatField()),
                ("minTemp_degC", models.IntegerField()),
                ("maxTemp_degC", models.IntegerField()),
                ("setTemp_degC", models.IntegerField()),
                ("lossFactor_WpK", models.FloatField()),
                ("heatCapacity_JpK", models.FloatField()),
                ("ambientTempType", models.CharField(max_length=100)),
            ],
            bases=("holon.storageasset",),
        ),
        migrations.CreateModel(
            name="NonFirmActor",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.actor",
                    ),
                ),
                ("nfATO_capacity_kw", models.FloatField()),
                ("nfATO_starttime", models.FloatField()),
                ("nfATO_endtime", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.actor",),
        ),
        migrations.CreateModel(
            name="ProductionAsset",
            fields=[
                (
                    "energyasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PHOTOVOLTAIC", "Photovoltaic"),
                            ("WINDMILL", "Windmill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.energyasset",),
        ),
        migrations.CreateModel(
            name="ProductionGridConnection",
            fields=[
                (
                    "gridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.gridconnection",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WINDFARM", "Windfarm"),
                            ("SOLARFARM", "Solarfarm"),
                            ("GRIDBATTERY", "Gridbattery"),
                        ],
                        max_length=11,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.gridconnection",),
        ),
        migrations.CreateModel(
            name="UtilityGridConnection",
            fields=[
                (
                    "gridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.gridconnection",
                    ),
                ),
                (
                    "heating_type",
                    models.CharField(
                        choices=[
                            ("GASBURNER", "Gasburner"),
                            ("GASFIRED", "Gasfired"),
                            ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                            ("DISTRICTHEAT", "Districtheat"),
                            ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                            ("HYDROGENFIRED", "Hydrogenfired"),
                            ("NONE", "None"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.gridconnection",),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.TextField()),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gridconnections",
                        to="holon.payload",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="gridnode",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.payload"
            ),
        ),
        migrations.AddField(
            model_name="gridnode",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.payload"
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("FIXED", "Fixed"),
                            ("VARIABLE", "Variable"),
                            ("DYNANMICDAYAHEAD", "Dynanmicdayahead"),
                            ("GOPACS", "Gopacs"),
                            ("NONFIRM", "Nonfirm"),
                            ("NODALPRICING", "Nodalpricing"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "contract_scope",
                    models.CharField(
                        choices=[
                            ("ENERGYSUPPLIER", "Energysupplier"),
                            ("GRIDOPERATOR", "Gridoperator"),
                            ("ENERGYHOLON", "Energyholon"),
                            ("ADMINISTRATIVEHOLON", "Administrativeholon"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="holon.actor",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.payload"
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.RemoveField(
            model_name="factor",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="factor",
            name="grid_connection",
        ),
        migrations.CreateModel(
            name="BuildingGridConnection",
            fields=[
                (
                    "builtenvironmentgridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.builtenvironmentgridconnection",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STORE", "Store"),
                            ("OFFICE", "Office"),
                            ("LOGISTICS", "Logistics"),
                        ],
                        max_length=9,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.builtenvironmentgridconnection",),
        ),
        migrations.CreateModel(
            name="DistrictHeatingGridConnection",
            fields=[
                (
                    "utilitygridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.utilitygridconnection",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("MT", "Mt"), ("HT", "Ht")], max_length=2
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.utilitygridconnection",),
        ),
        migrations.CreateModel(
            name="ElectricConsumptionAsset",
            fields=[
                (
                    "consumptionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.consumptionasset",
                    ),
                ),
                ("yearlyDemandElectricity_kWh", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.consumptionasset",),
        ),
        migrations.CreateModel(
            name="ElectricCoversionAsset",
            fields=[
                (
                    "conversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.conversionasset",
                    ),
                ),
                ("capacityElectricity_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.conversionasset",),
        ),
        migrations.CreateModel(
            name="ElectricProductionAsset",
            fields=[
                (
                    "productionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.productionasset",
                    ),
                ),
                ("capacityElectricity_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.productionasset",),
        ),
        migrations.CreateModel(
            name="HeatConsumptionAsset",
            fields=[
                (
                    "consumptionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.consumptionasset",
                    ),
                ),
                ("yearlyDemandHeat_kWh", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.consumptionasset",),
        ),
        migrations.CreateModel(
            name="HeatConversionAsset",
            fields=[
                (
                    "conversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.conversionasset",
                    ),
                ),
                ("deliveryTemp_degc", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.conversionasset",),
        ),
        migrations.CreateModel(
            name="HeatProductionAsset",
            fields=[
                (
                    "productionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.productionasset",
                    ),
                ),
                ("capacityHeat_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.productionasset",),
        ),
        migrations.CreateModel(
            name="HouseGridConnection",
            fields=[
                (
                    "builtenvironmentgridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.builtenvironmentgridconnection",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEMIDETACHED", "Semidetached"),
                            ("TERRACED", "Terraced"),
                            ("DETACHED", "Detached"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.builtenvironmentgridconnection",),
        ),
        migrations.CreateModel(
            name="HybridConsumptionAsset",
            fields=[
                (
                    "consumptionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.consumptionasset",
                    ),
                ),
                ("yearlyDemandHeat_kWh", models.FloatField()),
                ("yearlyDemandElectricity_kWh", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.consumptionasset",),
        ),
        migrations.CreateModel(
            name="HybridProductionAsset",
            fields=[
                (
                    "productionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.productionasset",
                    ),
                ),
                ("capacityElectricity_kW", models.FloatField()),
                ("capacityHeat_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.productionasset",),
        ),
        migrations.CreateModel(
            name="IndustryGridConnection",
            fields=[
                (
                    "utilitygridconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.utilitygridconnection",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STEEL", "Steel"),
                            ("INDUSTRY_OTHER", "Industry Other"),
                        ],
                        max_length=14,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.utilitygridconnection",),
        ),
        migrations.CreateModel(
            name="VehicleConversionAsset",
            fields=[
                (
                    "conversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.conversionasset",
                    ),
                ),
                ("energyConsumption_kWhpkm", models.FloatField()),
                ("vehicleScaling", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.conversionasset",),
        ),
        migrations.CreateModel(
            name="VehicleElectricStorageAsset",
            fields=[
                (
                    "electricstorageasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.electricstorageasset",
                    ),
                ),
                ("energyConsumption_kWhpkm", models.FloatField()),
                ("vehicleScaling", models.IntegerField()),
            ],
            bases=("holon.electricstorageasset",),
        ),
        migrations.DeleteModel(
            name="AssetOld",
        ),
        migrations.DeleteModel(
            name="GridConnectionOld",
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="parent_electric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.electricgridnode"
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="parent_heat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.heatgridnode"
            ),
        ),
        migrations.CreateModel(
            name="ChemicalHeatConversionAsset",
            fields=[
                (
                    "heatconversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.heatconversionasset",
                    ),
                ),
                ("capacityHeat_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.heatconversionasset",),
        ),
        migrations.CreateModel(
            name="ElectricHeatConversionAsset",
            fields=[
                (
                    "heatconversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.heatconversionasset",
                    ),
                ),
                ("capacityElectricity_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.heatconversionasset",),
        ),
        migrations.CreateModel(
            name="HybridHeatCoversionAsset",
            fields=[
                (
                    "heatconversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.heatconversionasset",
                    ),
                ),
                (
                    "ambientTempType",
                    models.CharField(
                        choices=[("AIR", "Air"), ("GROUND", "Ground")], max_length=255
                    ),
                ),
                ("capacityHeat_kW", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.heatconversionasset",),
        ),
        migrations.CreateModel(
            name="TransportHeatConversionAsset",
            fields=[
                (
                    "electricheatconversionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.electricheatconversionasset",
                    ),
                ),
                (
                    "ambientTempType",
                    models.CharField(
                        choices=[("AIR", "Air"), ("GROUND", "Ground")], max_length=255
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.electricheatconversionasset",),
        ),
    ]
