# Generated by Django 4.1.6 on 2023-02-10 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0003_actor_energyasset_gridconnection_gridnode_payload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHOICE_SINGLESELECT", "Single Select"),
                            ("CHOICE_MULTISELECT", "Multi Select"),
                            ("CHOICE_CONTINUOUS", "Continuous"),
                        ],
                        default="CHOICE_CONTINUOUS",
                        max_length=19,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("etm_scenario_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Scenario",
            },
        ),
        migrations.AlterModelOptions(
            name="electricstorageasset",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="heatstorageasset",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="storageasset",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="vehicleelectricstorageasset",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(
            model_name="storageasset",
            name="id",
        ),
        migrations.AddField(
            model_name="storageasset",
            name="energyasset_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="holon.energyasset",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="InteractiveElementOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "option",
                    models.CharField(help_text="Fill in your option", max_length=255),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Fill in the label that the user sees in a storyline",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        blank=True,
                        help_text="Should this option be default selected?",
                        null=True,
                    ),
                ),
                (
                    "input",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="holon.interactiveelement",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InteractiveElementContinuousValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_value_default",
                    models.IntegerField(
                        blank=True,
                        help_text="Default amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "slider_value_min",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Minimum amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "slider_value_max",
                    models.IntegerField(
                        blank=True,
                        default=100,
                        help_text="Maximum amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "input",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuous_values",
                        to="holon.interactiveelement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interactiveelement",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="gridnode",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gridconnections",
                to="holon.scenario",
            ),
        ),
        migrations.DeleteModel(
            name="Payload",
        ),
    ]
