# Generated by Django 4.1.7 on 2023-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0003_actor_anylogiccloudconfig_contract_energyasset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveelement",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "Level National"),
                    ("intermediate", "Level Intermediate"),
                    ("local", "Level Local"),
                ],
                help_text="If type is 'Continuous (slider)', choose a level. Otherwise, leave it empty",
                max_length=13,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interactiveelementoptions",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "Level National"),
                    ("intermediate", "Level Intermediate"),
                    ("local", "Level Local"),
                ],
                default="national",
                max_length=13,
                null=True,
            ),
        ),
    ]
