# Generated by Django 4.1.7 on 2023-03-13 12:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0004_alter_interactiveelement_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interactiveelementoptions",
            options={},
        ),
        migrations.RemoveField(
            model_name="scenariorule",
            name="interactive_element",
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="interactive_element_continuous_values",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="holon.interactiveelementcontinuousvalues",
            ),
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="interactive_element_option",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="holon.interactiveelementoptions",
            ),
        ),
    ]
