# Generated by Django 4.1.6 on 2023-02-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0004_interactiveelement_scenario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionasset",
            name="name",
        ),
        migrations.RemoveField(
            model_name="conversionasset",
            name="name",
        ),
        migrations.RemoveField(
            model_name="gridconnection",
            name="assets",
        ),
        migrations.RemoveField(
            model_name="productionasset",
            name="name",
        ),
        migrations.RemoveField(
            model_name="storageasset",
            name="name",
        ),
        migrations.AddField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.gridconnection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energyasset",
            name="name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="parent_electric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.electricgridnode",
            ),
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="parent_heat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.heatgridnode",
            ),
        ),
    ]
