# Generated by Django 4.1.7 on 2023-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0005_remove_consumptionasset_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="etm_scenario_id",
        ),
        migrations.AddField(
            model_name="scenario",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="version",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
