# Generated by Django 4.1.7 on 2023-02-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0005_remove_consumptionasset_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="type",
        ),
        migrations.AddField(
            model_name="actor",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[("COMMERCIAL", "Commercial"), ("HOUSEHOLD", "Household")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="subgroup",
            field=models.CharField(
                blank=True,
                choices=[("RICH", "Rich"), ("POOR", "Poor"), ("REGULAR", "Regular")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="energyasset",
            name="gridnode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridnode",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="category",
            field=models.CharField(
                choices=[
                    ("OPERATORGRID", "Operatorgrid"),
                    ("GOVHOLON", "Govholon"),
                    ("HOLONENERGY", "Holonenergy"),
                    ("CONNECTIONOWNER", "Connectionowner"),
                    ("SUPPLIERENERGY", "Supplierenergy"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
    ]
