# Generated by Django 4.1.7 on 2023-03-14 10:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0005_merge_20230314_1157"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleaction",
            name="asset_attribute",
        ),
        migrations.AddField(
            model_name="ruleactionchangeattribute",
            name="model_attribute",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ruleactionchangeattribute",
            name="operator",
            field=models.CharField(
                choices=[
                    ("=", "Set"),
                    ("+", "Add"),
                    ("-", "Subtract"),
                    ("*", "Multiply"),
                    ("/", "Divide"),
                ],
                default="=",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ruleactionfactor",
            name="model_attribute",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ruleactionchangeattribute",
            name="rule",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrete_factors_change_attribute",
                to="holon.scenariorule",
            ),
        ),
    ]
