# Generated by Django 4.1.6 on 2023-02-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("holon", "0005_remove_consumptionasset_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AttributeFilter",
            fields=[
                (
                    "filter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.filter",
                    ),
                ),
                ("model_attribute", models.CharField(max_length=255, null=True)),
                (
                    "comparator",
                    models.CharField(
                        choices=[
                            ("EQUAL", "Eq"),
                            ("LESS THAN", "Lt"),
                            ("GREATER THAN", "Gt"),
                            ("NOT EQUAL", "Ne"),
                        ],
                        max_length=255,
                    ),
                ),
                ("value", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.filter",),
        ),
        migrations.CreateModel(
            name="ScenarioRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("Actor", "Actor"),
                            ("EnergyAsset", "Energyasset"),
                            ("GridNode", "Gridnode"),
                            ("GridConnection", "Gridconnection"),
                            ("Policy", "Policy"),
                        ],
                        max_length=255,
                    ),
                ),
                ("model_subtype", models.CharField(max_length=255, null=True)),
                (
                    "interactive_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="holon.interactiveelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "ScenarioRule",
            },
        ),
        migrations.AddField(
            model_name="filter",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filters",
                to="holon.scenariorule",
            ),
        ),
        migrations.CreateModel(
            name="ParentAttributeFilter",
            fields=[
                (
                    "attributefilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.attributefilter",
                    ),
                ),
                ("parent_model_type", models.CharField(max_length=255, null=True)),
                ("parent_model_subtype", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.attributefilter",),
        ),
    ]
