# Generated by Django 4.1.6 on 2023-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0006_filter_attributefilter_scenariorule_filter_rule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariorule",
            name="model_subtype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
