# Generated by Django 4.1.7 on 2023-02-24 15:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0006_remove_scenario_etm_scenario_id_scenario_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnylogicCloudConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=40)),
                (
                    "url",
                    models.URLField(
                        default="https://engine.holontool.nl", max_length=100
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "model_version_number",
                    models.IntegerField(
                        help_text="Use this field to define the AnyLogic Cloud model version number"
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        help_text="This will be used to send the owner emails when things break",
                        max_length=254,
                    ),
                ),
                (
                    "scenario",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anylogic_config",
                        to="holon.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anylogic clouldclient configuratie",
            },
        ),
        migrations.CreateModel(
            name="CostBenifitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_attribute",
                    models.CharField(
                        default="asset_attribute_not_supplied", max_length=100
                    ),
                ),
                ("min_value", models.IntegerField()),
                ("max_value", models.IntegerField()),
            ],
            options={
                "verbose_name": "Kosten&baten configuratie",
            },
        ),
        migrations.CreateModel(
            name="ETMCostConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_attribute",
                    models.CharField(
                        default="asset_attribute_not_supplied", max_length=100
                    ),
                ),
                ("min_value", models.IntegerField()),
                ("max_value", models.IntegerField()),
            ],
            options={
                "verbose_name": "Kostenmodule configuratie",
            },
        ),
        migrations.CreateModel(
            name="ETMScalingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etm_scenario_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "ETM opschalingsconfiguratie",
            },
        ),
        migrations.CreateModel(
            name="AnylogicCloudOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anylogic_key", models.CharField(max_length=100)),
                ("internal_key", models.CharField(max_length=100)),
                (
                    "anylogic_model_configuration",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.anylogiccloudconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnylogicCloudInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anylogic_key", models.CharField(max_length=100)),
                ("anylogic_value", models.JSONField()),
                (
                    "anylogic_model_configuration",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.anylogiccloudconfig",
                    ),
                ),
            ],
        ),
    ]
