# Generated by Django 4.1.7 on 2023-03-15 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0007_alter_anylogiccloudoutput_anylogic_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heatconversionasset",
            old_name="deliveryTemp_degc",
            new_name="deliveryTemp_degC",
        ),
    ]
