# Generated by Django 4.1.6 on 2023-02-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0007_alter_scenariorule_model_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="rule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factors",
                to="holon.scenariorule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attributefilter",
            name="comparator",
            field=models.CharField(
                choices=[
                    ("EQUAL", "Equal"),
                    ("LESS THAN", "Less Than"),
                    ("GREATER THAN", "Greater Than"),
                    ("NOT EQUAL", "Not Equal"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenario"
            ),
        ),
        migrations.DeleteModel(
            name="ParentAttributeFilter",
        ),
    ]
