# Generated by Django 4.1.7 on 2023-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0007_alter_ruleactionbalancegroup_selected_model_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleactionbalancegroup",
            name="selected_model_type_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HeatStorageAsset", "HeatStorageAsset"),
                    ("HeatConversionAsset", "HeatConversionAsset"),
                    ("ElectricConsumptionAsset", "ElectricConsumptionAsset"),
                    ("ChemicalHeatConversionAsset", "ChemicalHeatConversionAsset"),
                    ("VehicleConversionAsset", "VehicleConversionAsset"),
                    ("HybridConsumptionAsset", "HybridConsumptionAsset"),
                    ("ConsumptionAsset", "ConsumptionAsset"),
                    ("VehicleElectricStorageAsset", "VehicleElectricStorageAsset"),
                    ("ElectricHeatConversionAsset", "ElectricHeatConversionAsset"),
                    ("HybridProductionAsset", "HybridProductionAsset"),
                    ("DieselVehicleAsset", "DieselVehicleAsset"),
                    ("StorageAsset", "StorageAsset"),
                    ("CookingConversionAsset", "CookingConversionAsset"),
                    ("TransportHeatConversionAsset", "TransportHeatConversionAsset"),
                    ("HybridHeatCoversionAsset", "HybridHeatCoversionAsset"),
                    ("ConversionAsset", "ConversionAsset"),
                    ("ElectricCoversionAsset", "ElectricCoversionAsset"),
                    ("ElectricProductionAsset", "ElectricProductionAsset"),
                    ("ProductionAsset", "ProductionAsset"),
                    ("HeatProductionAsset", "HeatProductionAsset"),
                    ("ElectricStorageAsset", "ElectricStorageAsset"),
                    ("HeatConsumptionAsset", "HeatConsumptionAsset"),
                    ("UtilityGridConnection", "UtilityGridConnection"),
                    ("IndustryGridConnection", "IndustryGridConnection"),
                    (
                        "BuiltEnvironmentGridConnection",
                        "BuiltEnvironmentGridConnection",
                    ),
                    ("DistrictHeatingGridConnection", "DistrictHeatingGridConnection"),
                    ("HouseGridConnection", "HouseGridConnection"),
                    ("BuildingGridConnection", "BuildingGridConnection"),
                    ("ProductionGridConnection", "ProductionGridConnection"),
                    ("DeliveryContract", "DeliveryContract"),
                    ("TransportContract", "TransportContract"),
                    ("TaxContract", "TaxContract"),
                    ("ConnectionContract", "ConnectionContract"),
                ],
                max_length=255,
            ),
        ),
    ]
