# Generated by Django 4.1.6 on 2023-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0007_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="max_value",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factor",
            name="min_value",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
