# Generated by Django 4.1.7 on 2023-02-24 15:11

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0007_anylogiccloudconfig_costbenifitconfig_etmcostconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costbenifitconfig",
            name="asset_attribute",
        ),
        migrations.RemoveField(
            model_name="costbenifitconfig",
            name="max_value",
        ),
        migrations.RemoveField(
            model_name="costbenifitconfig",
            name="min_value",
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="asset_attribute",
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="max_value",
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="min_value",
        ),
        migrations.AddField(
            model_name="costbenifitconfig",
            name="scenario",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_benefit_config",
                to="holon.scenario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etmcostconfig",
            name="scenario",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_cost_config",
                to="holon.scenario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etmscalingconfig",
            name="scenario",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_scaling_config",
                to="holon.scenario",
            ),
            preserve_default=False,
        ),
    ]
