# Generated by Django 4.1.6 on 2023-02-24 14:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("holon", "0008_factor_max_value_factor_min_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_attribute",
                    models.CharField(
                        default="asset_attribute_not_supplied", max_length=100
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.scenariorule",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleAction",
            },
        ),
        migrations.AlterField(
            model_name="factor",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.scenariorule"
            ),
        ),
        migrations.CreateModel(
            name="RuleActionAddRemove",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionAddRemove",
            },
            bases=("holon.ruleaction",),
        ),
        migrations.CreateModel(
            name="RuleActionBalanceGroup",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "assets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=255),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionBalanceGroup",
            },
            bases=("holon.ruleaction",),
        ),
        migrations.CreateModel(
            name="RuleActionChangeAttribute",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionChangeAttribute",
            },
            bases=("holon.ruleaction",),
        ),
        migrations.CreateModel(
            name="RuleActionFactor",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                ("min_value", models.IntegerField()),
                ("max_value", models.IntegerField()),
            ],
            options={
                "verbose_name": "RuleActionFactor",
            },
            bases=("holon.ruleaction",),
        ),
    ]
