# Generated by Django 4.1.7 on 2023-02-27 06:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0008_remove_costbenifitconfig_asset_attribute_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anylogiccloudconfig",
            options={"verbose_name": "Anylogic cloudclient configuratie"},
        ),
        migrations.RemoveField(
            model_name="costbenifitconfig",
            name="scenario",
        ),
        migrations.AddField(
            model_name="etmscalingconfig",
            name="api_url",
            field=models.URLField(
                default="https://beta-engine.energytransitionmodel.com/api/v3/scenarios/"
            ),
        ),
        migrations.AlterField(
            model_name="anylogiccloudinput",
            name="anylogic_model_configuration",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anylogic_cloud_input",
                to="holon.anylogiccloudconfig",
            ),
        ),
        migrations.AlterField(
            model_name="anylogiccloudinput",
            name="anylogic_value",
            field=models.JSONField(
                help_text="JSON format, will be parsed to be at available the same level in the JSON-payload as the other data"
            ),
        ),
        migrations.AlterField(
            model_name="anylogiccloudoutput",
            name="anylogic_key",
            field=models.CharField(
                help_text="Key as provided in the AnyLogic Cloud response JSON",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="anylogiccloudoutput",
            name="anylogic_model_configuration",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anylogic_cloud_output",
                to="holon.anylogiccloudconfig",
            ),
        ),
        migrations.AlterField(
            model_name="anylogiccloudoutput",
            name="internal_key",
            field=models.CharField(
                help_text="Key that is used internally to access the data associated with this AnyLogic key",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ETMQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_key",
                    models.CharField(
                        help_text="Key that is used internally (downstream) to access the data associated with this query result",
                        max_length=35,
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("input", "Input"),
                            ("query", "Query"),
                            ("curve", "Curve"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("value", "Value"), ("curve", "Curve")], max_length=255
                    ),
                ),
                (
                    "etm_key",
                    models.CharField(
                        help_text="Key as defined in the ETM", max_length=255
                    ),
                ),
                (
                    "etm_config",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etm_query",
                        to="holon.etmscalingconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ETMConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion",
                    models.CharField(
                        choices=[
                            ("multiply", "Multiply"),
                            ("divide", "Divide"),
                            ("add", "Add"),
                            ("substract", "Substract"),
                            ("in_product", "In Product"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "conversion_value_type",
                    models.CharField(
                        choices=[
                            ("static", "Static"),
                            ("query", "Query"),
                            ("curve", "Curve"),
                            ("anylogic_value", "Anylogic Value"),
                            ("anylogic_curve", "Anylogic Curve"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        blank=True,
                        help_text="Value for static conversions, only use when conversion type is static",
                        null=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Key as defined in the ETM or AnyLogic result data (only use when conversion type is not static)",
                        max_length=255,
                    ),
                ),
                (
                    "shadow_key",
                    models.CharField(
                        help_text="Internal key, not used by human but might occur in logs when errors occur",
                        max_length=255,
                    ),
                ),
                (
                    "etm_query",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_step",
                        to="holon.etmquery",
                    ),
                ),
            ],
        ),
    ]
