# Generated by Django 4.1.6 on 2023-02-27 22:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0009_ruleaction_alter_factor_rule_ruleactionaddremove_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interactiveelement",
            options={"verbose_name": "Interactive Element"},
        ),
        migrations.RemoveField(
            model_name="ruleaction",
            name="rule",
        ),
        migrations.AddField(
            model_name="ruleactionfactor",
            name="rule",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factors",
                to="holon.scenariorule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scenariorule",
            name="interactive_element",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="holon.interactiveelement",
            ),
        ),
    ]
