# Generated by Django 4.1.6 on 2023-03-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0009_ruleaction_alter_factor_rule_ruleactionaddremove_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ruleactionbalancegroup",
            old_name="assets",
            new_name="asset_order",
        ),
        migrations.AddField(
            model_name="ruleactionbalancegroup",
            name="selected_asset",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="energyassets",
                to="holon.gridconnection",
            ),
        ),
    ]
