# Generated by Django 4.1.6 on 2023-03-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0009_ruleaction_alter_factor_rule_ruleactionaddremove_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscreteAttributeFilter",
            fields=[
                (
                    "attributefilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.attributefilter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("holon.attributefilter",),
        ),
    ]
