# Generated by Django 4.1.7 on 2023-03-01 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0006_implements_module_config_in_cms"),
        ("holon", "0006_remove_actor_type_actor_group_actor_subgroup_and_more"),
        ("holon", "0009_ruleaction_alter_factor_rule_ruleactionaddremove_and_more"),
    ]

    operations = []
