# Generated by Django 4.1.7 on 2023-02-27 07:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0009_alter_anylogiccloudconfig_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etmquery",
            old_name="etm_config",
            new_name="related_config",
        ),
        migrations.RemoveField(
            model_name="etmconversion",
            name="key",
        ),
        migrations.RemoveField(
            model_name="etmconversion",
            name="value",
        ),
        migrations.AddField(
            model_name="etmconversion",
            name="etm_key",
            field=models.CharField(
                default="key_not_supplied",
                help_text="Key as defined in the ETM",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etmcostconfig",
            name="api_url",
            field=models.URLField(
                default="https://beta-engine.energytransitionmodel.com/api/v3/scenarios/"
            ),
        ),
        migrations.AddField(
            model_name="etmcostconfig",
            name="etm_scenario_id",
            field=models.IntegerField(default=2166341),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etmconversion",
            name="conversion_value_type",
            field=models.CharField(
                choices=[("value", "Value"), ("curve", "Curve")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="etmconversion",
            name="etm_query",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_conversion_step",
                to="holon.etmquery",
            ),
        ),
        migrations.AlterField(
            model_name="etmconversion",
            name="shadow_key",
            field=models.CharField(
                help_text="Internal key, not used by humans but might occur in logs when errors occur",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="StaticConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(help_text="Value for static conversions")),
                (
                    "conversion",
                    models.CharField(
                        choices=[
                            ("multiply", "Multiply"),
                            ("divide", "Divide"),
                            ("add", "Add"),
                            ("substract", "Substract"),
                            ("in_product", "In Product"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "shadow_key",
                    models.CharField(
                        help_text="Internal key, not used by humans but might occur in logs when errors occur",
                        max_length=255,
                    ),
                ),
                (
                    "etm_query",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_conversion_step",
                        to="holon.etmquery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatamodelConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion",
                    models.CharField(
                        choices=[
                            ("multiply", "Multiply"),
                            ("divide", "Divide"),
                            ("add", "Add"),
                            ("substract", "Substract"),
                            ("in_product", "In Product"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "conversion_value_type",
                    models.CharField(
                        choices=[("value", "Value"), ("curve", "Curve")], max_length=255
                    ),
                ),
                (
                    "filter",
                    models.CharField(
                        default="not_implemented",
                        help_text="Should be implemented as an inline panel that allows you to filter and select parts of the datamodel as you would",
                        max_length=255,
                    ),
                ),
                (
                    "self_conversion",
                    models.CharField(
                        choices=[("sum", "Sum"), ("count", "Count")],
                        help_text="Operation that is applied to the query set that results from the filter",
                        max_length=255,
                    ),
                ),
                (
                    "shadow_key",
                    models.CharField(
                        help_text="Internal key, not used by humans but might occur in logs when errors occur",
                        max_length=255,
                    ),
                ),
                (
                    "etm_query",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datamodel_conversion_step",
                        to="holon.etmquery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnyLogicConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion",
                    models.CharField(
                        choices=[
                            ("multiply", "Multiply"),
                            ("divide", "Divide"),
                            ("add", "Add"),
                            ("substract", "Substract"),
                            ("in_product", "In Product"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "conversion_value_type",
                    models.CharField(
                        choices=[("value", "Value"), ("curve", "Curve")], max_length=255
                    ),
                ),
                (
                    "anylogic_key",
                    models.CharField(
                        help_text="Key as defined in the AnyLogic results",
                        max_length=255,
                    ),
                ),
                (
                    "shadow_key",
                    models.CharField(
                        help_text="Internal key, not used by humans but might occur in logs when errors occur",
                        max_length=255,
                    ),
                ),
                (
                    "etm_query",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="al_conversion_step",
                        to="holon.etmquery",
                    ),
                ),
            ],
        ),
    ]
