# Generated by Django 4.1.6 on 2023-03-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0006_implements_module_config_in_cms"),
        ("holon", "0009_ruleaction_alter_factor_rule_ruleactionaddremove_and_more"),
    ]

    operations = []
