# Generated by Django 4.1.7 on 2023-02-27 08:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0010_rename_etm_config_etmquery_related_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryAndConvertConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        default="https://beta-engine.energytransitionmodel.com/api/v3/scenarios/"
                    ),
                ),
                ("etm_scenario_id", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="api_url",
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="etm_scenario_id",
        ),
        migrations.RemoveField(
            model_name="etmcostconfig",
            name="id",
        ),
        migrations.RemoveField(
            model_name="etmscalingconfig",
            name="api_url",
        ),
        migrations.RemoveField(
            model_name="etmscalingconfig",
            name="etm_scenario_id",
        ),
        migrations.RemoveField(
            model_name="etmscalingconfig",
            name="id",
        ),
        migrations.AddField(
            model_name="etmcostconfig",
            name="queryandconvertconfig_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="holon.queryandconvertconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etmscalingconfig",
            name="queryandconvertconfig_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="holon.queryandconvertconfig",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etmquery",
            name="related_config",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_query",
                to="holon.queryandconvertconfig",
            ),
        ),
    ]
