# Generated by Django 4.1.6 on 2023-03-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0010_rename_assets_ruleactionbalancegroup_asset_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ruleactionbalancegroup",
            old_name="asset_order",
            new_name="assets",
        ),
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="selected_asset",
        ),
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.gridconnection"
            ),
        ),
    ]
