# Generated by Django 4.1.6 on 2023-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0010_alter_interactiveelement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactiveelement",
            name="scenario",
        ),
        migrations.AlterField(
            model_name="attributefilter",
            name="model_attribute",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="interactiveelementoptions",
            name="default",
            field=models.BooleanField(
                default=False, help_text="Should this option be default selected?"
            ),
        ),
        migrations.AlterField(
            model_name="relationattributefilter",
            name="model_attribute",
            field=models.CharField(max_length=255),
        ),
    ]
