# Generated by Django 4.1.6 on 2023-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0010_discreteattributefilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builtenvironmentgridconnection",
            name="insulation_label",
            field=models.IntegerField(
                choices=[
                    (7, "A"),
                    (6, "B"),
                    (5, "C"),
                    (4, "D"),
                    (3, "E"),
                    (2, "F"),
                    (1, "G"),
                    (-1, "NONE"),
                ]
            ),
        ),
    ]
