# Generated by Django 4.1.6 on 2023-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0011_alter_etmquery_related_interactive_element"),
        ("holon", "0011_remove_interactiveelement_scenario_and_more"),
    ]

    operations = []
