# Generated by Django 4.1.7 on 2023-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "holon",
            "0008_rename_deliverytemp_degc_heatconversionasset_deliverytemp_degc",
        ),
        ("holon", "0011_merge_20230315_1354"),
    ]

    operations = []
