# Generated by Django 4.1.6 on 2023-03-03 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0011_rename_asset_order_ruleactionbalancegroup_assets_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="assets",
        ),
        migrations.AddField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=255),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ruleactionbalancegroup",
            name="selected_asset",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
