# Generated by Django 4.1.7 on 2023-02-27 10:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0011_queryandconvertconfig_remove_etmcostconfig_api_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etmscalingconfig",
            name="queryandconvertconfig_ptr",
        ),
        migrations.RemoveField(
            model_name="etmscalingconfig",
            name="scenario",
        ),
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="module",
            field=models.CharField(
                choices=[("upscaling", "Upscaling"), ("cost", "Cost")],
                default="upscaling",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="scenario",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_scaling_config",
                to="holon.scenario",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ETMCostConfig",
        ),
        migrations.DeleteModel(
            name="ETMScalingConfig",
        ),
    ]
