# Generated by Django 4.1.7 on 2023-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0011_remove_ruleactionbalancegroup_assets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="energyasset",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gridnode",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="wildcard_JSON",
            field=models.JSONField(
                blank=True,
                help_text="Use this field to define parameters that are not currently available in the datamodel.",
                null=True,
            ),
        ),
    ]
