# Generated by Django 4.1.6 on 2023-03-03 09:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0012_remove_ruleactionbalancegroup_assets_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ruleactionbalancegroup",
            old_name="selected_asset",
            new_name="selected_asset_type",
        ),
        migrations.AlterField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255), size=None
            ),
        ),
    ]
