# Generated by Django 4.1.7 on 2023-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0012_merge_20230316_1056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datamodelconversion",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="datamodelconversion",
            name="self_conversion",
        ),
        migrations.AlterField(
            model_name="datamodelconversion",
            name="conversion",
            field=models.CharField(choices=[("value", "Value")], max_length=255),
        ),
        migrations.AlterField(
            model_name="datamodelconversion",
            name="conversion_value_type",
            field=models.CharField(
                choices=[("multiply", "Multiply"), ("divide", "Divide")], max_length=255
            ),
        ),
    ]
