# Generated by Django 4.1.6 on 2023-03-06 14:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields

from holon.models.util import RemoveModelBasesOptions


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("holon", "0012_merge_20230306_1528"),
    ]

    operations = [
        RemoveModelBasesOptions("discreteattributefilter"),
        migrations.RemoveField(
            model_name="discreteattributefilter",
            name="attributefilter_ptr",
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="comparator",
            field=models.CharField(
                choices=[
                    ("EQUAL", "Equal"),
                    ("LESS THAN", "Less Than"),
                    ("GREATER THAN", "Greater Than"),
                    ("NOT EQUAL", "Not Equal"),
                ],
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="model_attribute",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="rule",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrete_attribute_filters",
                to="holon.scenariorule",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discreteattributefilter",
            name="value",
            field=models.JSONField(),
            preserve_default=False,
        ),
    ]
