# Generated by Django 4.1.7 on 2023-02-28 14:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0012_remove_etmscalingconfig_queryandconvertconfig_ptr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etmquery",
            old_name="query_type",
            new_name="endpoint",
        ),
        migrations.AlterField(
            model_name="anylogicconversion",
            name="conversion",
            field=models.CharField(
                choices=[
                    ("multiply", "Multiply"),
                    ("divide", "Divide"),
                    ("in_product", "In Product"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="datamodelconversion",
            name="conversion",
            field=models.CharField(
                choices=[
                    ("multiply", "Multiply"),
                    ("divide", "Divide"),
                    ("in_product", "In Product"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="etmconversion",
            name="conversion",
            field=models.CharField(
                choices=[
                    ("multiply", "Multiply"),
                    ("divide", "Divide"),
                    ("in_product", "In Product"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="scenario",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_and_convert_config",
                to="holon.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="staticconversion",
            name="conversion",
            field=models.CharField(
                choices=[
                    ("multiply", "Multiply"),
                    ("divide", "Divide"),
                    ("in_product", "In Product"),
                ],
                max_length=255,
            ),
        ),
    ]
