# Generated by Django 4.1.7 on 2023-03-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0012_actor_wildcard_json_contract_wildcard_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookingConversionAsset",
            fields=[
                (
                    "energyasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ELECTRIC_HOB", "Electric Hob"),
                            ("GAS_PIT", "Gas Pit"),
                        ],
                        max_length=255,
                    ),
                ),
                ("capacityHeat_kW", models.FloatField(blank=True, null=True)),
                ("capacityElectricity_kW", models.FloatField(blank=True, null=True)),
                ("eta_r", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.energyasset",),
        ),
        migrations.CreateModel(
            name="DieselVehicleAsset",
            fields=[
                (
                    "consumptionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.consumptionasset",
                    ),
                ),
                ("energyConsumption_kWhpkm", models.FloatField()),
                ("vehicleScaling", models.IntegerField()),
                ("eta_r", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.consumptionasset",),
        ),
        migrations.AddField(
            model_name="heatproductionasset",
            name="deliveryTemp_degC",
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name="consumptionasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY_DEMAND", "Electricity Demand"),
                    ("HEAT_DEMAND", "Heat Demand"),
                    ("HOT_WATER_CONSUMPTION", "Hot Water Consumption"),
                    ("OTHER_ELECTRICITY_CONSUMPTION", "Other Electricity Consumption"),
                    ("DIESEL_VEHICLE", "Diesel Vehicle"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="conversionasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("ELECTRIC_HEATER", "Electric Heater"),
                    ("GAS_BURNER", "Gas Burner"),
                    ("HEAT_DELIVERY_SET", "Heat Delivery Set"),
                    ("HEAT_PUMP_AIR", "Heat Pump Air"),
                    ("HEAT_PUMP_GROUND", "Heat Pump Ground"),
                    ("HEAT_PUMP_WATER", "Heat Pump Water"),
                    ("HYDROGEN_FURNACE", "Hydrogen Furnace"),
                    ("METHANE_FURNACE", "Methane Furnace"),
                    ("ELECTROLYSER", "Electrolyser"),
                    ("CURTAILER", "Curtailer"),
                    ("METHANE_CHP", "Methane Chp"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="productionasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("PHOTOVOLTAIC", "Photovoltaic"),
                    ("WINDMILL", "Windmill"),
                    ("RESIDUALHEATHT", "Residualheatht"),
                    ("RESIDUALHEATLT", "Residualheatlt"),
                ],
                max_length=20,
            ),
        ),
    ]
