# Generated by Django 4.1.6 on 2023-03-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "holon",
            "0013_rename_selected_asset_ruleactionbalancegroup_selected_asset_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.gridconnection",
            ),
        ),
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
        ),
        migrations.CreateModel(
            name="BalanceGroupAssetOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "balance_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.ruleactionbalancegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "BalanceGroupAssetOrder",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
            field=models.ManyToManyField(
                through="holon.BalanceGroupAssetOrder", to="holon.energyasset"
            ),
        ),
    ]
