# Generated by Django 4.1.7 on 2023-03-01 08:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0013_rename_query_type_etmquery_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="KeyValuePairCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_config",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_value_pair_collection",
                        to="holon.queryandconvertconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETM module configuratie variabelen",
            },
        ),
        migrations.CreateModel(
            name="FloatKeyValuePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                (
                    "related_key_value_collection",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="float_key_value_pair",
                        to="holon.keyvaluepaircollection",
                    ),
                ),
            ],
        ),
    ]
