# Generated by Django 4.1.6 on 2023-03-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0011_remove_interactiveelement_scenario_and_more"),
        ("holon", "0014_alter_energyasset_gridconnection_and_more"),
    ]

    operations = []
