# Generated by Django 4.1.7 on 2023-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0014_rule_remove_scenariorule_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamodelconversion",
            name="conversion",
            field=models.CharField(
                choices=[("multiply", "Multiply"), ("divide", "Divide")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="datamodelconversion",
            name="conversion_value_type",
            field=models.CharField(choices=[("value", "Value")], max_length=255),
        ),
    ]
