# Generated by Django 4.1.7 on 2023-03-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0014_queryandconvertconfig_name_keyvaluepaircollection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticconversion",
            name="local_variable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.floatkeyvaluepair",
            ),
        ),
        migrations.AlterField(
            model_name="staticconversion",
            name="value",
            field=models.FloatField(
                help_text="Value for static conversions", null=True
            ),
        ),
    ]
