# Generated by Django 4.1.7 on 2023-03-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0014_alter_etmquery_related_interactive_element"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="parent_actor",
        ),
        migrations.AddField(
            model_name="contract",
            name="contractScope_new",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.PROTECT, to="holon.actor"
            ),
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contractScope",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="contractScope_new",
            new_name="contractScope",
        ),
    ]
