# Generated by Django 4.1.7 on 2023-03-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0014_remove_dieselvehicleasset_eta_r"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildinggridconnection",
            name="heatmodel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.heatstorageasset",
            ),
        ),
        migrations.AddField(
            model_name="heatstorageasset",
            name="initial_temperature_degC",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="housegridconnection",
            name="heatmodel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="holon.heatstorageasset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storageasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("ELECTRIC_VEHICLE", "Electric Vehicle"),
                    ("STORAGE_ELECTRIC", "Storage Electric"),
                    ("STORAGE_HEAT", "Storage Heat"),
                    ("HEATMODEL", "Heatmodel"),
                ],
                max_length=50,
            ),
        ),
    ]
