# Generated by Django 4.1.6 on 2023-03-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0014_alter_energyasset_gridconnection_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RuleActionAddRemove",
            new_name="RuleActionRemove",
        ),
        migrations.AlterModelOptions(
            name="ruleactionremove",
            options={"verbose_name": "RuleActionRemove"},
        ),
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
        ),
        migrations.CreateModel(
            name="RuleActionAdd",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.energyasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionAdd",
            },
            bases=("holon.ruleaction",),
        ),
    ]
