# Generated by Django 4.1.7 on 2023-03-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0015_alter_datamodelconversion_conversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_rule_action_template",
            field=models.BooleanField(
                default=False,
                help_text="Set this to True when this model can be used as a template for rule actions",
            ),
        ),
        migrations.AddField(
            model_name="energyasset",
            name="is_rule_action_template",
            field=models.BooleanField(
                default=False,
                help_text="Set this to True when this model can be used as a template for rule actions",
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="is_rule_action_template",
            field=models.BooleanField(
                default=False,
                help_text="Set this to True when this model can be used as a template for rule actions",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.actorgroup",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.actorsubgroup",
            ),
        ),
        migrations.AlterField(
            model_name="balancegroupmodelorder",
            name="asset_to_balance",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.energyasset",
            ),
        ),
        migrations.AlterField(
            model_name="balancegroupmodelorder",
            name="contract_to_balance",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.contract",
            ),
        ),
        migrations.AlterField(
            model_name="balancegroupmodelorder",
            name="gridconnection_to_balance",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="holon.actor",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contractScope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holon.actor"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contractType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DELIVERY", "Delivery"),
                    ("TRANSPORT", "Transport"),
                    ("CONNECTION", "Connection"),
                    ("TAX", "Tax"),
                ],
                default="DELIVERY",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="owner_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.actor",
            ),
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="payload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionadd",
            name="asset_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.energyasset",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionadd",
            name="contract_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.contract",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionadd",
            name="gridconnection_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionsetcount",
            name="asset_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.energyasset",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionsetcount",
            name="contract_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.contract",
            ),
        ),
        migrations.AlterField(
            model_name="ruleactionsetcount",
            name="gridconnection_to_add",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_rule_action_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
    ]
