# Generated by Django 4.1.7 on 2023-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0015_staticconversion_local_variable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticconversion",
            name="value",
            field=models.FloatField(
                blank=True, help_text="Value for static conversions", null=True
            ),
        ),
    ]
