# Generated by Django 4.1.6 on 2023-03-06 13:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0015_merge_20230306_1203"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancegroupassetorder",
            options={"verbose_name": "BalanceGroupAssetOrder"},
        ),
        migrations.RemoveField(
            model_name="balancegroupassetorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="asset_order",
        ),
        migrations.AddField(
            model_name="balancegroupassetorder",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="ruleactionbalancegroup",
            name="assets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=255), size=None
                ),
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="balancegroupassetorder",
            name="balance_group",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_group_asset_order",
                to="holon.ruleactionbalancegroup",
            ),
        ),
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.gridconnection",
            ),
        ),
    ]
