# Generated by Django 4.1.7 on 2023-03-16 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0012_merge_20230316_1046"),
        ("holon", "0015_alter_datamodelconversion_conversion_and_more"),
    ]

    operations = []
