# Generated by Django 4.1.7 on 2023-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0015_buildinggridconnection_heatmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildinggridconnection",
            name="heatmodel",
        ),
        migrations.RemoveField(
            model_name="housegridconnection",
            name="heatmodel",
        ),
        migrations.AlterField(
            model_name="heatstorageasset",
            name="ambientTempType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="heatstorageasset",
            name="initial_temperature_degC",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="heatstorageasset",
            name="setTemp_degC",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
