# Generated by Django 4.1.6 on 2023-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0015_rename_ruleactionaddremove_ruleactionremove_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleactionadd",
            name="interactive_element_max_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ruleactionadd",
            name="invert_add_value",
            field=models.BooleanField(default=False),
        ),
    ]
