# Generated by Django 4.1.6 on 2023-03-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0016_alter_balancegroupassetorder_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleactionbalancegroup",
            name="assets",
        ),
    ]
