# Generated by Django 4.1.6 on 2023-03-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0016_ruleactionadd_interactive_element_max_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleactionadd",
            name="interactive_element_max_value",
        ),
        migrations.RemoveField(
            model_name="ruleactionadd",
            name="invert_add_value",
        ),
    ]
