# Generated by Django 4.1.7 on 2023-03-20 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0016_alter_actor_group_alter_actor_subgroup_and_more"),
        ("holon", "0016_contract_is_rule_action_template_and_more"),
    ]

    operations = []
