# Generated by Django 4.1.6 on 2023-03-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0011_alter_etmquery_related_interactive_element"),
        ("holon", "0017_remove_ruleactionbalancegroup_assets"),
    ]

    operations = []
