# Generated by Django 4.1.7 on 2023-03-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0017_merge_20230320_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contractScope",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="holon.actor"
            ),
        ),
    ]
