# Generated by Django 4.1.6 on 2023-03-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0017_remove_ruleactionadd_interactive_element_max_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleactionadd",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.contract",
            ),
        ),
        migrations.AddField(
            model_name="ruleactionadd",
            name="gridconnection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.gridconnection",
            ),
        ),
    ]
