# Generated by Django 4.1.7 on 2023-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0017_alter_staticconversion_local_variable"),
    ]

    operations = [
        migrations.AddField(
            model_name="etmquery",
            name="interactive_upscaling_comment",
            field=models.CharField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. Use {{variable}} for dynamic values. Options: local key-value pairs e.g., `scaling_factor`, `final_value` or `query_value` (to be implemented)",
                max_length=350,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="etmquery",
            name="related_interactive_element",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this field to relate this query and conversion set to an interactive element (used for rendering in the front-end)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.interactiveelement",
            ),
        ),
    ]
