# Generated by Django 4.1.7 on 2023-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0013_remove_discreteattributefilter_attributefilter_ptr_and_more"),
        ("holon", "0015_remove_actor_parent_actor_contract_contractscope_new"),
        ("holon", "0017_remove_ruleactionbalancegroup_assets"),
    ]

    operations = []
