# Generated by Django 4.1.7 on 2023-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0018_alter_contract_contractscope"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleactionremove",
            name="remove_mode",
            field=models.CharField(
                choices=[
                    ("remove_all", "Remove All"),
                    ("remove_n", "Remove N"),
                    ("keep_n", "Keep N"),
                ],
                default="remove_all",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
