# Generated by Django 4.1.7 on 2023-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0018_connectioncontract_deliverycontract_taxcontract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildinggridconnection",
            name="type",
            field=models.CharField(
                choices=[
                    ("STORE", "Store"),
                    ("OFFICE", "Office"),
                    ("LOGISTICS", "Logistics"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gridconnection",
            name="charging_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAX_POWER", "Max Power"),
                    ("MAX_SPREAD", "Max Spread"),
                    ("CHEAP", "Cheap"),
                    ("SIMPLE", "Simple"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="housegridconnection",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEMIDETACHED", "Semidetached"),
                    ("TERRACED", "Terraced"),
                    ("DETACHED", "Detached"),
                ],
                max_length=100,
            ),
        ),
    ]
