# Generated by Django 4.1.6 on 2023-03-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0018_ruleactionadd_contract_ruleactionadd_gridconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleaction",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.scenariorule",
            ),
        ),
        migrations.CreateModel(
            name="RuleActionSetCount",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "rule_action_add",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.ruleactionadd",
                    ),
                ),
                (
                    "rule_action_remove",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holon.ruleactionremove",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionSetCount",
            },
            bases=("holon.ruleaction",),
        ),
    ]
