# Generated by Django 4.1.7 on 2023-03-24 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0018_alter_contract_contractscope"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interactiveelementoptions",
            options={"ordering": ["sort_order"]},
        ),
    ]
