# Generated by Django 4.1.6 on 2023-03-07 12:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0018_merge_20230307_1249"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleActionAdd",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.contract",
                    ),
                ),
                (
                    "gridconnection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.gridconnection",
                    ),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrete_factors_add",
                        to="holon.scenariorule",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionAdd",
            },
            bases=("holon.ruleaction", models.Model),
        ),
        migrations.CreateModel(
            name="RuleActionRemove",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrete_factors_remove",
                        to="holon.scenariorule",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionRemove",
            },
            bases=("holon.ruleaction",),
        ),
        migrations.CreateModel(
            name="RuleActionSetCount",
            fields=[
                (
                    "ruleaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.ruleaction",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.energyasset",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.contract",
                    ),
                ),
                (
                    "gridconnection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="holon.gridconnection",
                    ),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrete_factors_set_count",
                        to="holon.scenariorule",
                    ),
                ),
            ],
            options={
                "verbose_name": "RuleActionSetCount",
            },
            bases=("holon.ruleaction", models.Model),
        ),
        migrations.DeleteModel(
            name="RuleActionAddRemove",
        ),
    ]
