# Generated by Django 4.1.7 on 2023-03-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_interactiveelementunit"),
        ("holon", "0018_alter_contract_contractscope"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelementcontinuousvalues",
            name="slider_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.interactiveelementunit",
            ),
        ),
    ]
