# Generated by Django 4.1.6 on 2023-03-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0018_merge_20230307_1520"),
        ("holon", "0019_ruleactionadd_ruleactionremove_ruleactionsetcount_and_more"),
    ]

    operations = []
