# Generated by Django 4.1.6 on 2023-03-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0019_alter_ruleaction_rule_ruleactionsetcount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleactionsetcount",
            name="rule_action_remove",
        ),
    ]
