# Generated by Django 4.1.7 on 2023-03-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0019_alter_interactiveelementoptions_options"),
        ("holon", "0019_ruleactionremove_remove_mode"),
    ]

    operations = []
