# Generated by Django 4.1.6 on 2023-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0020_merge_20230307_1608"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CostBenifitConfig",
        ),
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="module",
            field=models.CharField(
                choices=[
                    ("upscaling", "Upscaling"),
                    ("cost", "Cost"),
                    ("costbenifit", "Costbenifit"),
                ],
                max_length=255,
            ),
        ),
    ]
