# Generated by Django 4.1.7 on 2023-03-28 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0019_interactiveelementcontinuousvalues_slider_unit"),
        ("holon", "0020_merge_20230327_1111"),
    ]

    operations = []
