# Generated by Django 4.1.7 on 2023-03-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0021_alter_heatgridnode_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builtenvironmentgridconnection",
            name="heating_type",
            field=models.CharField(
                choices=[
                    ("GASBURNER", "Gasburner"),
                    ("GASFIRED", "Gasfired"),
                    ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                    ("DISTRICTHEAT", "Districtheat"),
                    ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                    ("HYDROGENFIRED", "Hydrogenfired"),
                    ("GASFIRED_CHPPEAK", "Gasfired Chppeak"),
                    ("LT_RESIDUAL_HEATPUMP_GASPEAK", "Lt Residual Heatpump Gaspeak"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="districtheatinggridconnection",
            name="type",
            field=models.CharField(
                choices=[("MT", "Mt"), ("HT", "Ht"), ("LT", "Lt")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="housegridconnection",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEMIDETACHED", "Semidetached"),
                    ("TERRACED", "Terraced"),
                    ("DETACHED", "Detached"),
                    ("HIGHRISE", "Highrise"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="industrygridconnection",
            name="type",
            field=models.CharField(
                choices=[("STEEL", "Steel"), ("INDUSTRY_OTHER", "Industry Other")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="productiongridconnection",
            name="category",
            field=models.CharField(
                choices=[
                    ("WINDFARM", "Windfarm"),
                    ("SOLARFARM", "Solarfarm"),
                    ("GRIDBATTERY", "Gridbattery"),
                    ("RESIDUALHEAT", "Residualheat"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="utilitygridconnection",
            name="heating_type",
            field=models.CharField(
                choices=[
                    ("GASBURNER", "Gasburner"),
                    ("GASFIRED", "Gasfired"),
                    ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                    ("DISTRICTHEAT", "Districtheat"),
                    ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                    ("HYDROGENFIRED", "Hydrogenfired"),
                    ("GASFIRED_CHPPEAK", "Gasfired Chppeak"),
                    ("LT_RESIDUAL_HEATPUMP_GASPEAK", "Lt Residual Heatpump Gaspeak"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
    ]
