# Generated by Django 4.1.7 on 2023-03-28 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0021_merge_20230328_1122"),
        ("holon", "0021_scenario_cloned_from"),
    ]

    operations = []
