# Generated by Django 4.1.7 on 2023-03-28 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0023_alter_rule_model_type"),
        ("holon", "0023_ruleactionaddmultipleundereachparent"),
    ]

    operations = []
