# Generated by Django 4.1.7 on 2023-03-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0024_merge_20230328_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleactionchangeattribute",
            name="static_value",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
