# Generated by Django 4.1.7 on 2023-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0025_ruleactionchangeattribute_static_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleactionchangeattribute",
            name="static_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
