# Generated by Django 4.1.7 on 2023-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0027_contract_name"),
        ("holon", "0028_alter_filtersubselector_number_of_items"),
    ]

    operations = []
