# Generated by Django 4.1.7 on 2023-04-05 09:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("holon", "0030_alter_contract_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueTransform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ValueTranslate",
            fields=[
                (
                    "valuetransform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.valuetransform",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(verbose_name="Amount to add (or subtract)"),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_translates",
                        to="holon.rule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.valuetransform",),
        ),
        migrations.CreateModel(
            name="ValueScale",
            fields=[
                (
                    "valuetransform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.valuetransform",
                    ),
                ),
                ("factor", models.FloatField(verbose_name="Scaling factor")),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scales",
                        to="holon.rule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.valuetransform",),
        ),
        migrations.CreateModel(
            name="ValueRound",
            fields=[
                (
                    "valuetransform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.valuetransform",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ROUND", "Round"),
                            ("CEIL", "Ceil"),
                            ("FLOOR", "Floor"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_rounds",
                        to="holon.rule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.valuetransform",),
        ),
        migrations.CreateModel(
            name="ValueMapRange",
            fields=[
                (
                    "valuetransform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.valuetransform",
                    ),
                ),
                (
                    "value_min",
                    models.FloatField(verbose_name="Minimum possible input value"),
                ),
                (
                    "value_max",
                    models.FloatField(verbose_name="Maximum possible input value"),
                ),
                (
                    "new_range_min",
                    models.FloatField(verbose_name="Minimum output value"),
                ),
                (
                    "new_range_max",
                    models.FloatField(verbose_name="Maximum output value"),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_map_ranges",
                        to="holon.rule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.valuetransform",),
        ),
    ]
