# Generated by Django 4.1.8 on 2023-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0031_relationattributefilter_invert_filter_and_more"),
        ("holon", "0031_valuetransform_valuetranslate_valuescale_valueround_and_more"),
    ]

    operations = []
