# Generated by Django 4.1.7 on 2023-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0032_merge_20230406_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="energyasset",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gridconnection",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gridnode",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="original_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="This field is used as a reference for cloned models. Don't set it manually",
                null=True,
            ),
        ),
    ]
