# Generated by Django 4.1.7 on 2023-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0032_merge_20230406_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="module",
            field=models.CharField(
                choices=[
                    ("upscaling", "Upscaling"),
                    ("upscaling-regional", "Upscaling Regional"),
                    ("cost", "Cost"),
                    ("costbenefit", "Costbenefit"),
                ],
                max_length=255,
            ),
        ),
    ]
