# Generated by Django 4.1.7 on 2023-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0032_merge_20230406_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="etmquery",
            name="interactive_upscaling_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the explaination of upscaling. For instance, the category of the upscaling component ('Zon op dak').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="interactive_upscaling_comment",
            field=models.CharField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. This field is rendered next to the KPI selection radio (that toggles between local, intermediate and national level)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="module",
            field=models.CharField(
                choices=[
                    ("upscaling", "Upscaling"),
                    ("upscaling-regional", "Upscaling Regional"),
                    ("cost", "Cost"),
                    ("costbenefit", "Costbenefit"),
                ],
                max_length=255,
            ),
        ),
    ]
