# Generated by Django 4.1.7 on 2023-04-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0033_actor_original_id_contract_original_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builtenvironmentgridconnection",
            name="heating_type",
            field=models.CharField(
                choices=[
                    ("GASBURNER", "Gasburner"),
                    ("GASFIRED", "Gasfired"),
                    ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                    ("DISTRICTHEAT", "Districtheat"),
                    ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                    ("HYDROGENFIRED", "Hydrogenfired"),
                    ("GASFIRED_CHPPEAK", "Gasfired Chppeak"),
                    ("DISTRICT_EBOILER_CHP", "District Eboiler Chp"),
                    ("HEATPUMP_AIR", "Heatpump Air"),
                    ("DISTRICTHEATDECENTRAL", "Districtheatdecentral"),
                    ("LT_RESIDUAL_HEATPUMP_GASPEAK", "Lt Residual Heatpump Gaspeak"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="utilitygridconnection",
            name="heating_type",
            field=models.CharField(
                choices=[
                    ("GASBURNER", "Gasburner"),
                    ("GASFIRED", "Gasfired"),
                    ("HEATPUMP_GASPEAK", "Heatpump Gaspeak"),
                    ("DISTRICTHEAT", "Districtheat"),
                    ("HEATPUMP_BOILERPEAK", "Heatpump Boilerpeak"),
                    ("HYDROGENFIRED", "Hydrogenfired"),
                    ("GASFIRED_CHPPEAK", "Gasfired Chppeak"),
                    ("DISTRICT_EBOILER_CHP", "District Eboiler Chp"),
                    ("HEATPUMP_AIR", "Heatpump Air"),
                    ("DISTRICTHEATDECENTRAL", "Districtheatdecentral"),
                    ("LT_RESIDUAL_HEATPUMP_GASPEAK", "Lt Residual Heatpump Gaspeak"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
    ]
