# Generated by Django 4.1.7 on 2023-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0033_etmquery_interactive_upscaling_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etmquery",
            name="interactive_upscaling_comment",
            field=models.TextField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. Use {{variable}} for dynamic values. Options: local key-value pairs e.g., `scaling_factor`, `final_value` or `query_value` (to be implemented)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="interactive_upscaling_comment",
            field=models.TextField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. This field is rendered next to the KPI selection radio (that toggles between local, intermediate and national level)",
                max_length=255,
                null=True,
            ),
        ),
    ]
