# Generated by Django 4.1.7 on 2023-04-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0034_alter_etmquery_interactive_upscaling_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericETMQuery",
            fields=[
                (
                    "etmquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.etmquery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("holon.etmquery",),
        ),
        migrations.AddField(
            model_name="etmquery",
            name="generic",
            field=models.BooleanField(
                default=False, verbose_name="Generic ETM query snippet"
            ),
        ),
    ]
