# Generated by Django 4.1.7 on 2023-04-07 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0035_genericetmquery_etmquery_generic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etmquery",
            name="generic",
        ),
    ]
