# Generated by Django 4.1.7 on 2023-04-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0035_secondorderrelationattributefilter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secondorderrelationattributefilter",
            options={"verbose_name": "SecondOrderRelationAttributeFilter"},
        ),
    ]
