# Generated by Django 4.1.7 on 2023-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0036_remove_etmquery_generic"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="related_interactive_element",
            field=models.ManyToManyField(
                blank=True,
                help_text="Use this field to relate this module configuration to a generic ETM query.",
                to="holon.genericetmquery",
            ),
        ),
    ]
