# Generated by Django 4.1.8 on 2023-04-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0036_alter_secondorderrelationattributefilter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="holon.actor",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contractScope",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holon.actor",
            ),
        ),
    ]
