# Generated by Django 4.1.8 on 2023-04-24 10:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0037_alter_contract_actor_alter_contract_contractscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericETMQuery",
            fields=[
                (
                    "etmquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.etmquery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("holon.etmquery",),
        ),
        migrations.AddField(
            model_name="etmquery",
            name="interactive_upscaling_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the explaination of upscaling. For instance, the category of the upscaling component ('Zon op dak').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="interactive_upscaling_comment",
            field=models.TextField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. This field is rendered next to the KPI selection radio (that toggles between local, intermediate and national level)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="etmquery",
            name="interactive_upscaling_comment",
            field=models.TextField(
                blank=True,
                help_text="Use this field to explain the query in the front-end. Use {{variable}} for dynamic values. Options: local key-value pairs e.g., `scaling_factor`, `final_value` or `query_value` (to be implemented)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="etmquery",
            name="related_config",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_query",
                to="holon.queryandconvertconfig",
            ),
        ),
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="module",
            field=models.CharField(
                choices=[
                    ("upscaling", "Upscaling"),
                    ("upscaling-regional", "Upscaling Regional"),
                    ("cost", "Cost"),
                    ("costbenefit", "Costbenefit"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="queryandconvertconfig",
            name="generic_etm_query",
            field=models.ManyToManyField(
                blank=True,
                help_text="Use this field to relate this module configuration to a generic ETM query.",
                to="holon.genericetmquery",
            ),
        ),
    ]
