# Generated by Django 4.1.7 on 2023-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0037_queryandconvertconfig_related_interactive_element"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queryandconvertconfig",
            old_name="related_interactive_element",
            new_name="generic_etm_query",
        ),
    ]
