# Generated by Django 4.1.8 on 2023-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0037_alter_contract_actor_alter_contract_contractscope"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelementcontinuousvalues",
            name="discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="Number of steps the slider has. Leave empty or 0 to let the slider be contiuous.",
                null=True,
            ),
        ),
    ]
