# Generated by Django 4.1.8 on 2023-04-25 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0038_genericetmquery_etmquery_interactive_upscaling_title_and_more"),
        ("holon", "0038_interactiveelementcontinuousvalues_discretization_steps"),
    ]

    operations = []
