# Generated by Django 4.1.7 on 2023-04-07 15:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "holon",
            "0038_rename_related_interactive_element_queryandconvertconfig_generic_etm_query",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="etmquery",
            name="related_config",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etm_query",
                to="holon.queryandconvertconfig",
            ),
        ),
    ]
