# Generated by Django 4.1.9 on 2023-06-01 13:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0039_merge_20230425_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="generic_etm_query",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Use this field to relate this module configuration to a generic ETM query.",
                to="holon.genericetmquery",
            ),
        ),
    ]
