# Generated by Django 4.1.8 on 2023-04-24 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0037_alter_contract_actor_alter_contract_contractscope"),
        ("holon", "0039_alter_etmquery_related_config"),
    ]

    operations = []
