# Generated by Django 4.1.9 on 2023-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0043_filtersubselector_amount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filtersubselector",
            name="amount_type",
            field=models.CharField(
                choices=[("ABSOLUTE", "Absolute"), ("RELATIVE", "Relative")],
                default="ABSOLUTE",
                max_length=32,
                verbose_name="Absolute number of items or percentage of total selection (number between 0 and 100)",
            ),
        ),
        migrations.AlterField(
            model_name="filtersubselector",
            name="number_of_items",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="number or percentage of items (leave empty if using interactive element value)",
            ),
        ),
    ]
