# Generated by Django 4.1.9 on 2023-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0045_ruleactionattributenoise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleactionattributenoise",
            name="max_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ruleactionattributenoise",
            name="mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ruleactionattributenoise",
            name="min_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ruleactionattributenoise",
            name="sigma",
            field=models.FloatField(default=0.0),
        ),
    ]
