# Generated by Django 4.1.9 on 2023-06-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0046_alter_ruleactionattributenoise_max_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="payload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("Actor", "Actor"),
                    ("Contract", "Contract"),
                    ("EnergyAsset", "Energyasset"),
                    ("GridNode", "Gridnode"),
                    ("GridConnection", "Gridconnection"),
                    ("Policy", "Policy"),
                    ("Scenario", "Scenario"),
                ],
                max_length=255,
            ),
        ),
    ]
