# Generated by Django 4.1.9 on 2023-06-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0047_alter_actor_payload_alter_rule_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyasset",
            name="gridconnection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.gridconnection",
            ),
        ),
        migrations.AlterField(
            model_name="energyasset",
            name="gridnode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holon.gridnode",
            ),
        ),
    ]
