# Generated by Django 4.1.9 on 2023-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0047_alter_actor_payload_alter_rule_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildinggridconnection",
            name="type",
            field=models.CharField(
                choices=[
                    ("STORE", "Store"),
                    ("OFFICE", "Office"),
                    ("LOGISTICS", "Logistics"),
                    ("FARM", "Farm"),
                    ("VILLAGE", "Village"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="housegridconnection",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEMIDETACHED", "Semidetached"),
                    ("TERRACED", "Terraced"),
                    ("DETACHED", "Detached"),
                    ("APPARTMENT", "Appartment"),
                    ("HIGHRISE", "Highrise"),
                    ("NONE", "None"),
                ],
                max_length=100,
            ),
        ),
    ]
