# Generated by Django 4.1.9 on 2023-06-15 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0048_alter_buildinggridconnection_type_and_more"),
        ("holon", "0050_alter_rule_model_type"),
    ]

    operations = []
