# Generated by Django 4.1.9 on 2023-06-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0049_alter_interactiveelement_more_information"),
        ("holon", "0051_merge_20230615_1246"),
    ]

    operations = []
