# Generated by Django 4.1.9 on 2023-06-16 09:23

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0051_merge_20230615_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamodelqueryrule",
            name="datamodel_conversion_step",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datamodel_query_rule",
                to="holon.datamodelconversion",
                unique=True,
            ),
        ),
    ]
