# Generated by Django 4.1.9 on 2023-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0052_alter_datamodelqueryrule_datamodel_conversion_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactiveelementcontinuousvalues",
            name="discretization_steps",
        ),
        migrations.AddField(
            model_name="interactiveelementcontinuousvalues",
            name="sandbox_discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="Sandbox Discretization steps: Number of steps the slider has. Leave empty or 0 to let the slider be contiuous.",
                null=True,
            ),
        ),
    ]
