# Generated by Django 4.1.9 on 2023-06-20 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0052_alter_datamodelqueryrule_datamodel_conversion_step"),
        ("holon", "0052_merge_20230616_1035"),
    ]

    operations = []
