# Generated by Django 4.1.9 on 2023-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "holon",
            "0053_remove_interactiveelementcontinuousvalues_discretization_steps_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelementcontinuousvalues",
            name="discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="Number of steps the slider has. Leave empty or 0 to let the slider be contiuous.",
                null=True,
            ),
        ),
    ]
