# Generated by Django 4.1.9 on 2023-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0054_interactiveelementcontinuousvalues_discretization_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveelementcontinuousvalues",
            name="discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Storyline and challenge discretization steps: Number of steps the slider has. Leave empty or 0 to let the slider be contiuous.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interactiveelementcontinuousvalues",
            name="sandbox_discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Sandbox discretization steps: Number of steps the slider has. Leave empty or 0 to let the slider be contiuous.",
                null=True,
            ),
        ),
    ]
