# Generated by Django 4.1.9 on 2023-06-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0053_merge_20230620_1336"),
        (
            "holon",
            "0055_alter_interactiveelementcontinuousvalues_discretization_steps_and_more",
        ),
    ]

    operations = []
