# Generated by Django 4.1.9 on 2023-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0056_merge_20230620_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveelementcontinuousvalues",
            name="discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Storyline and challenge discretization steps: Amount of steps the slider has. Leave empty to let the slider be contiuous.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interactiveelementcontinuousvalues",
            name="sandbox_discretization_steps",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Sandbox discretization steps: Amount of steps the slider has. Leave empty to let the slider be contiuous.",
                null=True,
            ),
        ),
    ]
