# Generated by Django 4.1.9 on 2023-06-21 09:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0057_alter_interactiveelementcontinuousvalues_discretization_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datamodelqueryrule",
            name="self_conversion_factor",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="datamodelqueryrule",
            name="datamodel_conversion_step",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datamodel_query_rule",
                to="holon.datamodelconversion",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="RuleActionConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("static_value", models.FloatField(blank=True, null=True)),
                (
                    "conversion_with_static",
                    models.CharField(
                        blank=True,
                        choices=[("multiply", "Multiply"), ("sum", "Sum")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "conversion_between_rules",
                    models.CharField(
                        choices=[("multiply", "Multiply"), ("sum", "Sum")],
                        max_length=255,
                    ),
                ),
                (
                    "rule_action_change_attribute",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_action_conversion_step",
                        to="holon.ruleactionchangeattribute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="datamodelqueryrule",
            name="rule_action_conversion_step",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_action_datamodel_query_rule",
                to="holon.ruleactionconversion",
            ),
        ),
    ]
