# Generated by Django 4.1.10 on 2023-08-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0058_datamodelqueryrule_self_conversion_factor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydrogenConsumptionAsset",
            fields=[
                (
                    "consumptionasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="holon.consumptionasset",
                    ),
                ),
                ("yearlyDemandHydrogen_kWh", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("holon.consumptionasset",),
        ),
        migrations.AlterField(
            model_name="consumptionasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY_DEMAND", "Electricity Demand"),
                    ("HEAT_DEMAND", "Heat Demand"),
                    ("HOT_WATER_CONSUMPTION", "Hot Water Consumption"),
                    ("OTHER_ELECTRICITY_CONSUMPTION", "Other Electricity Consumption"),
                    ("DIESEL_VEHICLE", "Diesel Vehicle"),
                    ("DIESEL_DEMAND", "Diesel Demand"),
                    ("METHANE_DEMAND", "Methane Demand"),
                    ("HYDROGEN_DEMAND", "Hydrogen Demand"),
                ],
                max_length=255,
            ),
        ),
    ]
