# Generated by Django 4.1.10 on 2023-10-06 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holon", "0059_hydrogenconsumptionasset_alter_consumptionasset_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={"ordering": ["id"], "verbose_name": "Rule"},
        ),
    ]
