# Generated by Django 4.2.6 on 2023-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holon', '0060_alter_rule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryandconvertconfig',
            name='api_url',
            field=models.URLField(db_comment='This is currently not used and should be removed', default='https://beta-engine.energytransitionmodel.com/api/v3/scenarios/'),
        ),
    ]
