# Generated by Django 4.2.6 on 2024-04-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0061_alter_queryandconvertconfig_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryandconvertconfig",
            name="api_url",
            field=models.URLField(
                default="https://engine.energytransitionmodel.com/api/v3/scenarios/"
            ),
        ),
    ]
