# Generated by Django 4.1.2 on 2022-10-18 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="slider_locked",
            field=models.BooleanField(default=False, help_text="Show locked solarpanel slider"),
        ),
        migrations.AddField(
            model_name="slider",
            name="slider_value_default",
            field=models.IntegerField(
                blank=True,
                help_text="Default amount of solarpanels",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="slider",
            name="slider_value_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum amount of solarpanels",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="slider",
            name="slider_value_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum amount of solarpanels",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="slider",
            name="tag",
            field=models.CharField(
                choices=[("solar", "Solarpanels"), ("windmills", "Windmills")],
                default="solar",
                max_length=50,
            ),
        ),
    ]
