# Generated by Django 4.1.2 on 2022-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_slider_slider_locked_slider_slider_value_default_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Scenario",
            },
        ),
        migrations.RemoveField(
            model_name="slider",
            name="slider_locked",
        ),
        migrations.AlterField(
            model_name="slider",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[("solar", "Solarpanels"), ("windmills", "Windmills")],
                help_text="Which part of the animation does this slider relate to",
                max_length=50,
                null=True,
            ),
        ),
    ]
