# Generated by Django 4.1.3 on 2022-11-17 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_scenario_remove_slider_slider_locked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox"),
                            ("multibutton", "Multibutton"),
                            ("radio", "Radiobutton"),
                            ("button", "Button"),
                            ("continuous", "Continuous (slider)"),
                        ],
                        default="continuous",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Input",
            },
        ),
        migrations.CreateModel(
            name="InteractiveInputOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "option",
                    models.CharField(help_text="Fill in your option", max_length=255),
                ),
                (
                    "input",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.interactiveinput",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InteractiveInputContinuousValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_value_default",
                    models.IntegerField(
                        blank=True,
                        help_text="Default amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "slider_value_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "slider_value_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum amount of the continuous input",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "input",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuous_values",
                        to="api.interactiveinput",
                    ),
                ),
            ],
        ),
    ]
