# Generated by Django 4.1.3 on 2022-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_scenario_remove_slider_slider_locked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Interactive Input",
            },
        ),
    ]
