# Generated by Django 4.1.2 on 2022-10-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holon", "0001_initial"),
        ("api", "0003_scenario_remove_slider_slider_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="holon.scenariotag",
            ),
        ),
    ]
