# Generated by Django 4.1.3 on 2022-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_interactiveinput"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinput",
            name="type",
            field=models.CharField(
                choices=[
                    ("checkbox", "Checkbox"),
                    ("multibutton", "Multibutton"),
                    ("radio", "Radiobutton"),
                    ("button", "Button"),
                    ("continuous", "Continuous (slider)"),
                ],
                default="continuous",
                max_length=12,
            ),
        ),
    ]
