# Generated by Django 4.1.3 on 2022-11-24 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_merge_20221122_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinput",
            name="asset_type",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveinput",
            name="etm_key",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="interactiveinputcontinuousvalues",
            name="slider_value_max",
            field=models.IntegerField(
                blank=True,
                default=100,
                help_text="Maximum amount of the continuous input",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="interactiveinputcontinuousvalues",
            name="slider_value_min",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Minimum amount of the continuous input",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
