# Generated by Django 4.1.3 on 2022-12-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_interactiveinputoptions_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveinputoptions",
            name="default",
            field=models.BooleanField(
                blank=True,
                help_text="Should this option be default selected?",
                null=True,
            ),
        ),
    ]
