# Generated by Django 4.1.5 on 2023-01-06 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_interactiveinputoptions_default"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Slider",
        ),
    ]
