# Generated by Django 4.1.5 on 2023-01-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_wikipage_table"),
        ("api", "0010_delete_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="color",
            field=models.CharField(
                choices=[
                    ("no-color", "Geen kleur"),
                    ("red", "Rood"),
                    ("orange", "Oranje"),
                    ("limegreen", "Groen"),
                ],
                default="no-color",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="legal_limitation",
            field=models.CharField(
                blank=True,
                help_text="Fill in the status of the legal limitation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="link_wiki_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to link to an internal page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.wikipage",
            ),
        ),
    ]
