# Generated by Django 4.1.5 on 2023-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_delete_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="color",
            field=models.CharField(
                choices=[
                    ("no-color", "Geen kleur"),
                    ("red", "Rood"),
                    ("orange", "Oranje"),
                    ("green", "Groen"),
                ],
                default="no-color",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="legal_limitation",
            field=models.CharField(
                blank=True,
                help_text="Fill in the status of the legal limitation",
                max_length=255,
                null=True,
            ),
        ),
    ]
