# Generated by Django 4.1.5 on 2023-01-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_interactiveinputoptions_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveinputoptions",
            name="color",
            field=models.CharField(
                choices=[
                    ("no-color", "Geen kleur"),
                    ("red", "Rood"),
                    ("orange", "Oranje"),
                    ("limegreen", "Groen"),
                ],
                default="no-color",
                max_length=10,
                null=True,
            ),
        ),
    ]
