# Generated by Django 4.1.5 on 2023-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_interactiveinputoptions_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveinputoptions",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No color"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("limegreen", "Green"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
