# Generated by Django 4.1.6 on 2023-02-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_interactiveinputoptions_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactiveinput",
            name="asset_type",
        ),
    ]
