# Generated by Django 4.1.5 on 2023-01-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_wikipage_table"),
        ("api", "0012_alter_interactiveinputoptions_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="link_wiki_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to link to an internal page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="title_wiki_page",
            field=models.CharField(
                blank=True,
                help_text="Fill in an informative title for the wikipage you link to",
                max_length=150,
                null=True,
            ),
        ),
    ]
