# Generated by Django 4.1.5 on 2023-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_interactiveinputoptions_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinput",
            name="more_information",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
