# Generated by Django 4.1.5 on 2023-02-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_merge_20230130_1024"),
        ("api", "0013_interactiveinput_more_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinput",
            name="link_wiki_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to link to an internal wiki page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.wikipage",
            ),
        ),
    ]
