# Generated by Django 4.1.6 on 2023-02-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_interactiveinput_link_wiki_page_and_more"),
        ("api", "0013_remove_interactiveinput_asset_type"),
    ]

    operations = []
