# Generated by Django 4.1.6 on 2023-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_interactiveinput_link_wiki_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinputoptions",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("intermediate", "Intermediate"),
                    ("local", "Local"),
                ],
                max_length=13,
                null=True,
            ),
        ),
    ]
