# Generated by Django 4.1.6 on 2023-02-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_interactiveinputoptions_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveinputoptions",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("intermediate", "Intermediate"),
                    ("local", "Local"),
                ],
                default="national",
                max_length=13,
                null=True,
            ),
        ),
    ]
