# Generated by Django 4.1.7 on 2023-03-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_interactiveinput_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactiveinput",
            name="asset_type",
        ),
    ]
