# Generated by Django 4.1.6 on 2023-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_merge_20230210_1042"),
        ("api", "0017_alter_interactiveinput_level"),
    ]

    operations = []
