# Generated by Django 4.1.7 on 2023-03-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_interactiveelementunit"),
        ("api", "0018_alter_interactiveinput_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveinputcontinuousvalues",
            name="slider_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.interactiveelementunit",
            ),
        ),
    ]
