from django.test import TestCase
from holon.models.scenario import Scenario
from holon.services.costs_table import CostTables


class CostTableTestClass(TestCase):
    fixtures = ["holon/tests/fixtures/merged-datamodel-ehub-config-fixture.json"]

    def test_table_totals(self):
        """Test if the totals table is correctly set up"""
        scenario = Scenario.objects.get(pk=1)
        tables = CostTables.from_al_output(self.__al_output(), scenario)
        costs_table = tables.main_table()

        assert "Bedrijventerrein HOLON" in costs_table.keys()
        assert "CONNECTIONOWNER" in costs_table.keys()
        assert "OPERATORGRID" in costs_table.keys()

        detailed_table = tables.detailed_table("Commercieel bedrijf 1")
        assert "Commercieel bedrijf 1 - poor" in detailed_table.keys()
        assert "Commercieel bedrijf 1 - rich" in detailed_table.keys()

        detailed_tables = tables.all_detailed_tables()
        assert "Commercieel bedrijf 1" in detailed_tables.keys()
        assert "Commercieel bedrijf 2" not in detailed_tables.keys()

    def __al_output(self):
        return [
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con4",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con4",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 20.0,
                "nfATOend_h": 7.0,
                "nfATOpower_kW": 2000.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con4",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con4",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con5",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con5",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 20.0,
                "nfATOend_h": 7.0,
                "nfATOpower_kW": 2000.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con5",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con5",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": -467137.9985450749,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 0.0,
                "nfATOend_h": 0.0,
                "nfATOpower_kW": 0.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": -219082.7197801406,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "METHANE",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 6315962.061147418,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 0.0,
                "nfATOend_h": 0.0,
                "nfATOpower_kW": 0.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "METHANE",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 6315962.061147418,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con6",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.01,
                "feedinTax_eurpkWh": 0.0,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con7",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 0.0,
                "nfATOend_h": 0.0,
                "nfATOpower_kW": 0.0,
            },
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con7",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con7",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con7",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "HYDROGEN",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con7",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 0.0,
                "nfATOend_h": 0.0,
                "nfATOpower_kW": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "CONNECTION",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con8",
                "annualFee_eur": 0.0,
                "connectionContractType": "DEFAULT",
                "nfATOstart_h": 0.0,
                "nfATOend_h": 0.0,
                "nfATOpower_kW": 0.0,
            },
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con8",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con8",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "con8",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "sup3",
                "energyCarrier": "ELECTRICITY",
                "contractType": "DELIVERY",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "hol2",
                "annualFee_eur": 0.0,
                "deliveryContractType": "ELECTRICITY_VARIABLE",
                "deliveryPrice_eurpkWh": 0.0,
                "feedinPrice_eurpkWh": 0.0,
            },
            {
                "contractScope": "ope1",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TRANSPORT",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "hol2",
                "annualFee_eur": 0.0,
                "transportContractType": "DEFAULT",
                "bandwidthTreshold_kW": 0.0,
                "bandwidthTariff_eurpkWh": 0.0,
            },
            {
                "contractScope": "gov9",
                "energyCarrier": "ELECTRICITY",
                "contractType": "TAX",
                "EnergyTransactionVolume_kWh": 0.0,
                "FinancialTransactionVolume_eur": 0.0,
                "contractHolder": "hol2",
                "annualFee_eur": 0.0,
                "deliveryTax_eurpkWh": 0.15,
                "feedinTax_eurpkWh": 0.15,
                "proportionalTax_pct": 0.21,
            },
        ]
