# Generated by Django 4.1.2 on 2022-10-12 09:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_wikipage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorylinePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "storyline",
                    wagtail.fields.StreamField(
                        [
                            (
                                "intro",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.CharBlock()),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyline",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
    ]
