# Generated by Django 4.1.2 on 2022-10-12 13:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_wikipage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
    ]
