# Generated by Django 4.1.2 on 2022-10-12 12:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_wikipage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorylinePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyline",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="basepage_ptr",
        ),
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.DeleteModel(
            name="ArticlePage",
        ),
    ]
