# Generated by Django 4.1.2 on 2022-10-12 14:14

from django.db import migrations
import main.blocks.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_aboutpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default theme"),
                                                        ("primary", "Primary"),
                                                        ("secondary", "Secondary"),
                                                        ("light", "Light"),
                                                        ("dark", "Dark"),
                                                        ("white", "White"),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                ("text", main.blocks.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default theme"),
                                                        ("primary", "Primary"),
                                                        ("secondary", "Secondary"),
                                                        ("light", "Light"),
                                                        ("dark", "Dark"),
                                                        ("white", "White"),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                ("text", main.blocks.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
    ]
