# Generated by Django 4.1.2 on 2022-10-12 09:43

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_storylinepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storylinepage",
            name="storyline",
            field=wagtail.fields.StreamField(
                [
                    (
                        "intro",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.CharBlock()),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "scenario",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("scenario-1", "Scenario 1"),
                                            ("scenario-2", "Scenario 2"),
                                            ("scenario-3", "Scenario 3"),
                                        ]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ("text", wagtail.blocks.RichTextBlock()),
                                            (
                                                "slider",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "visible",
                                                            wagtail.blocks.BooleanBlock(),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=None,
            ),
        ),
    ]
