# Generated by Django 4.1.2 on 2022-10-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_scenario_remove_slider_slider_locked_and_more"),
        ("main", "0005_storylinepage_scenario_alter_storylinepage_storyline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storylinepage",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.scenario",
            ),
        ),
    ]
