# Generated by Django 4.1.2 on 2022-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_homepage_body_alter_aboutpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="body",
        ),
    ]
