# Generated by Django 4.1.3 on 2022-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_storylineoverviewpage"),
        ("main", "0006_alter_storylinepage_scenario"),
    ]

    operations = []
