# Generated by Django 4.1.2 on 2022-10-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_storylineoverviewpage"),
        ("main", "0006_alter_storylinepage_scenario"),
    ]

    operations = []
