# Generated by Django 4.1.3 on 2022-11-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_scenariolistpage_scenariopage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenariopage",
            name="basepage_ptr",
        ),
        migrations.DeleteModel(
            name="ScenariolistPage",
        ),
        migrations.DeleteModel(
            name="ScenarioPage",
        ),
    ]
