# Generated by Django 4.1.3 on 2022-11-03 15:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0003_alter_customimage_file_hash"),
        ("main", "0007_merge_20221103_1604"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorylinePageInformationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=255)),
            ],
            options={
                "verbose_name": "Storyline InformationType",
                "verbose_name_plural": "Storyline InformationTypes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorylinePageRoleType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=255)),
            ],
            options={
                "verbose_name": "Storyline Roletype",
                "verbose_name_plural": "Storyline Rolestypes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="card_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card__bg-gold", "Gold"),
                    ("card__bg-blue", "Blue"),
                    ("card__bg-gray", "Gray"),
                    ("card__bg-purple", "Purple"),
                    ("card__bg-pink", "Pink"),
                    ("card__bg-orange", "Orange"),
                ],
                default="card__bg-blue",
                help_text="Background color in storyline overview page",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the storyline", null=True
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customimage.customimage",
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="information_types",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.storylinepageinformationtype"
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="roles",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.storylinepageroletype"
            ),
        ),
    ]
