# Generated by Django 4.1.2 on 2022-10-13 14:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default theme"),
                                                        (
                                                            "bg-purple-100",
                                                            "prime color",
                                                        ),
                                                        ("bg-violet-500", "soft color"),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
    ]
