# Generated by Django 4.1.2 on 2022-10-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_storylinepage_scenario"),
        ("main", "0008_alter_homepage_body"),
    ]

    operations = []
