# Generated by Django 4.1.2 on 2022-10-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_storylinepage_description_storylinepage_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorylinePageCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="A slug to identify a model by this category",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyline Category",
                "verbose_name_plural": "Storyline Categories",
                "ordering": ["name"],
            },
        ),
    ]
