# Generated by Django 4.1.3 on 2022-11-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_storylinepageinformationtype_storylinepageroletype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storylinepage",
            name="card_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("green", "GREEN"),
                    ("blue", "BLUE"),
                    ("red", "RED"),
                    ("orange", "ORANGE"),
                    ("black", "BLACK"),
                ],
                default="green",
                help_text="Background color in storyline overview page",
                max_length=6,
            ),
        ),
    ]
