# Generated by Django 4.1.2 on 2022-10-25 06:07

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_storylinepagecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="storylinepage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.storylinepagecategory"
            ),
        ),
        migrations.AlterField(
            model_name="storylinepage",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
