# Generated by Django 4.1.3 on 2022-11-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_storylinepageinformationtype_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storylineoverviewpage",
            name="storyline",
        ),
    ]
