# Generated by Django 4.1.3 on 2022-11-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_storylinepage_card_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storylinepage",
            name="card_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bg-holon-gold-200", "Gold"),
                    ("bg-holon-blue-100", "Blue"),
                    ("bg-holon-gray-100", "Gray"),
                    ("bg-holon-purple-100", "Purple"),
                    ("bg-holon-pink-100", "Pink"),
                    ("bg-holon-orange-100", "Orange"),
                ],
                default="green",
                help_text="Background color in storyline overview page",
                max_length=20,
            ),
        ),
    ]
