# Generated by Django 4.1.2 on 2022-10-25 13:52

from django.db import migrations
import main.blocks.blocks
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default color"),
                                                        (
                                                            "holon-gold-200",
                                                            "prime color",
                                                        ),
                                                        (
                                                            "holon-blue-900",
                                                            "soft color",
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "hero_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default color"),
                                                        (
                                                            "holon-gold-200",
                                                            "prime color",
                                                        ),
                                                        (
                                                            "holon-blue-900",
                                                            "soft color",
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=True)),
                                (
                                    "image_selector",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default color"),
                                                        (
                                                            "holon-gold-200",
                                                            "prime color",
                                                        ),
                                                        (
                                                            "holon-blue-900",
                                                            "soft color",
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "image_selector",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock()),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "button_color",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "select_background",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "",
                                                                        "Default color",
                                                                    ),
                                                                    (
                                                                        "holon-gold-200",
                                                                        "prime color",
                                                                    ),
                                                                    (
                                                                        "holon-blue-900",
                                                                        "soft color",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "button_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button size"),
                                                        ("btn-sm", "small"),
                                                        ("btn-lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_hyperlink",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "card_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Card: Text below image"),
                                            ("tile", "Tile: Text over image"),
                                        ],
                                        help_text="",
                                        required=False,
                                    ),
                                ),
                                (
                                    "className",
                                    wagtail.blocks.CharBlock(
                                        form_classname="className",
                                        help_text="default 2 cards in single row (col-md-6), add tailwind classes to change",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "head",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "image_selector",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "image",
                                                                main.blocks.blocks.ImageChooserBlock(
                                                                    required=True
                                                                ),
                                                            ),
                                                            (
                                                                "caption",
                                                                wagtail.blocks.CharBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "attribution",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "subtitle",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "button_text",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="The url of the image hyperlink will be used for this button",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "button_color",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "select_background",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "",
                                                                        "Default color",
                                                                    ),
                                                                    (
                                                                        "holon-gold-200",
                                                                        "prime color",
                                                                    ),
                                                                    (
                                                                        "holon-blue-900",
                                                                        "soft color",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "button_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button size"),
                                                        ("btn-sm", "small"),
                                                        ("btn-lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_hyperlink",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_video_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "select_background",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default color"),
                                                        (
                                                            "holon-gold-200",
                                                            "prime color",
                                                        ),
                                                        (
                                                            "holon-blue-900",
                                                            "soft color",
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    "embed_video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        max_height=400, max_width=800
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
    ]
