# Generated by Django 4.1.3 on 2022-11-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_storylinepage_card_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storylinepage",
            name="card_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card__bg-gold", "Gold"),
                    ("card__bg-blue", "Blue"),
                    ("card__bg-gray", "Gray"),
                    ("card__bg-purple", "Purple"),
                    ("card__bg-pink", "Pink"),
                    ("card__bg-orange", "Orange"),
                ],
                default="green",
                help_text="Background color in storyline overview page",
                max_length=20,
            ),
        ),
    ]
