# Generated by Django 4.1.3 on 2022-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_storylinepage_card_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="storylinepageinformationtype",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("book", "Book"),
                    ("bell", "Bell"),
                    ("cog", "Cog"),
                    ("folder", "Folder"),
                    ("heart", "Heart"),
                    ("info", "Info"),
                    ("lightning", "Lightning bolt"),
                    ("mapmarker", "Map marker"),
                    ("rocket", "Rocket"),
                    ("star", "Star"),
                    ("user", "User"),
                ],
                default="green",
                help_text="Icon shown in storyline overview page",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storylinepageroletype",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("book", "Book"),
                    ("bell", "Bell"),
                    ("cog", "Cog"),
                    ("folder", "Folder"),
                    ("heart", "Heart"),
                    ("info", "Info"),
                    ("lightning", "Lightning bolt"),
                    ("mapmarker", "Map marker"),
                    ("rocket", "Rocket"),
                    ("star", "Star"),
                    ("user", "User"),
                ],
                default="green",
                help_text="Icon shown in storyline overview page",
                max_length=20,
            ),
        ),
    ]
