# Generated by Django 4.1.3 on 2022-11-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_homepage_content_alter_staticpage_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticTermPage",
            fields=[
                (
                    "staticpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.staticpage",
                    ),
                ),
                (
                    "introduction",
                    models.CharField(
                        help_text="Text used in the highlight on other pages",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "StaticTermPage",
            },
            bases=("main.staticpage",),
        ),
    ]
