# Generated by Django 4.1.3 on 2022-11-16 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_homepage_content_alter_staticpage_content_and_more"),
        ("main", "0014_storylineoverviewpage_body_and_more"),
    ]

    operations = []
