# Generated by Django 4.1.3 on 2022-11-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_storylineoverviewpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storylineoverviewpage",
            name="body",
        ),
    ]
