# Generated by Django 4.1.2 on 2022-11-01 10:16

from django.db import migrations
import main.blocks.blocks
import main.blocks.storyline_section
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("bg-holon-gray-100", "Pale gray"),
                                            ("bg-holon-purple-100", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "hero_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "block_background",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("bg-holon-gray-100", "Pale gray"),
                                            ("bg-holon-purple-100", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=True)),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "button_style",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button style"),
                                                        ("btn-dark", "dark"),
                                                        ("btn-light", "light"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button size"),
                                                        ("btn-sm", "small"),
                                                        ("btn-lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_hyperlink",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_selector",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock()),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "button_style",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button style"),
                                                        ("btn-dark", "dark"),
                                                        ("btn-light", "light"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button size"),
                                                        ("btn-sm", "small"),
                                                        ("btn-lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_hyperlink",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "card_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Card: Text below image"),
                                            ("tile", "Tile: Text over image"),
                                        ],
                                        help_text="",
                                        required=False,
                                    ),
                                ),
                                (
                                    "className",
                                    wagtail.blocks.CharBlock(
                                        form_classname="className",
                                        help_text="default 2 cards in single row (col-md-6), add tailwind classes to change",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "head",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "image_selector",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "image",
                                                                main.blocks.blocks.ImageChooserBlock(
                                                                    required=True
                                                                ),
                                                            ),
                                                            (
                                                                "caption",
                                                                wagtail.blocks.CharBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "attribution",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "subtitle",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "button_text",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="The url of the image hyperlink will be used for this button",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "card_background",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("bg-holon-gray-100", "Pale gray"),
                                            ("bg-holon-purple-100", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "button_style",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button style"),
                                                        ("btn-dark", "dark"),
                                                        ("btn-light", "light"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=True,
                                                    choices=[
                                                        ("", "Default button size"),
                                                        ("btn-sm", "small"),
                                                        ("btn-lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "button_text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_hyperlink",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="storylinepage",
            name="storyline",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text_and_media",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Add your text",
                                        required=True,
                                        rows=15,
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "grid_layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("25_75", "25% - 75%"),
                                            ("50_50", "50% - 50%"),
                                            ("75_25", "75% - 25%"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ("text", wagtail.blocks.RichTextBlock()),
                                            (
                                                "slider",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "slider",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=main.blocks.storyline_section.get_sliders
                                                            ),
                                                        ),
                                                        (
                                                            "visible",
                                                            wagtail.blocks.BooleanBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "locked",
                                                            wagtail.blocks.BooleanBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
