# Generated by Django 4.1.3 on 2022-11-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_statictermpage"),
        ("main", "0016_remove_storylineoverviewpage_body_and_more"),
    ]

    operations = []
