# Generated by Django 4.1.3 on 2022-11-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_homepage_content_alter_staticpage_content_and_more"),
        ("main", "0016_remove_storylineoverviewpage_body_and_more"),
    ]

    operations = []
