# Generated by Django 4.1.3 on 2022-11-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_storylinepage_storyline"),
        ("main", "0016_remove_storylineoverviewpage_body_and_more"),
    ]

    operations = []
