# Generated by Django 4.1.3 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_merge_20221117_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="introduction",
            field=models.CharField(
                default="",
                help_text="Text used in the highlight on other pages",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StaticTermPage",
        ),
    ]
