# Generated by Django 4.1.3 on 2022-11-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_storylinepage_storyline"),
        ("main", "0018_wikipage_introduction_delete_statictermpage"),
    ]

    operations = []
