# Generated by Django 4.1.3 on 2022-11-25 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_homepage_content_alter_staticpage_content_and_more"),
        ("main", "0020_alter_storylinepage_storyline"),
    ]

    operations = []
