# Generated by Django 4.1.3 on 2022-12-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_storylinepage_storyline"),
        ("main", "0027_alter_homepage_content_alter_staticpage_content_and_more"),
    ]

    operations = []
