# Generated by Django 4.1.5 on 2023-01-10 08:32

from django.db import migrations, models
import django.db.models.deletion
import main.blocks.holon_image_chooser
import main.blocks.page_chooser_block
import main.blocks.rich_text_block
import main.blocks.storyline_section
import modelcluster.fields
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_delete_slider"),
        ("customimage", "0003_alter_customimage_file_hash"),
        ("main", "0028_alter_storylinepage_storyline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storylinepageinformationtype",
            options={
                "ordering": ["name"],
                "verbose_name": "InformationType",
                "verbose_name_plural": "InformationTypes",
            },
        ),
        migrations.AlterModelOptions(
            name="storylinepageroletype",
            options={
                "ordering": ["name"],
                "verbose_name": "Roletype",
                "verbose_name_plural": "Rolestypes",
            },
        ),
        migrations.CreateModel(
            name="ChallengeModePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the storyline", null=True
                    ),
                ),
                (
                    "card_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card__bg-gold", "Gold"),
                            ("card__bg-blue", "Blue"),
                            ("card__bg-gray", "Gray"),
                            ("card__bg-purple", "Purple"),
                            ("card__bg-pink", "Pink"),
                            ("card__bg-orange", "Orange"),
                        ],
                        default="card__bg-blue",
                        help_text="Background color in storyline overview page",
                        max_length=20,
                    ),
                ),
                (
                    "storyline",
                    wagtail.fields.StreamField(
                        [
                            (
                                "header_full_image_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                blank=True,
                                                choices=[
                                                    ("", "Select header size"),
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                ],
                                            ),
                                        ),
                                        (
                                            "image_selector",
                                            main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "text_and_media",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "grid_layout",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "grid",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("33_66", "33% - 66%"),
                                                                ("50_50", "50% - 50%"),
                                                                ("66_33", "66% - 33%"),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "column_order",
                                            wagtail.blocks.ChoiceBlock(
                                                blank=True,
                                                choices=[
                                                    (
                                                        "",
                                                        "Default (Text left, Media right)",
                                                    ),
                                                    (
                                                        "invert",
                                                        "Invert columns (Media left, Text right)",
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "color",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "block__bg-white",
                                                                    "White",
                                                                ),
                                                                (
                                                                    "block__bg-gray",
                                                                    "Pale gray",
                                                                ),
                                                                (
                                                                    "block__bg-purple",
                                                                    "Pale purple",
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "size",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "bg__full",
                                                                    "Full backgroundcolor",
                                                                ),
                                                                (
                                                                    "bg__left",
                                                                    "Only backgroundcolor in the left block",
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "text",
                                            main.blocks.rich_text_block.RichtextBlock(
                                                help_text="Add your text",
                                                required=True,
                                                rows=15,
                                            ),
                                        ),
                                        (
                                            "media",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "image",
                                                        main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "video",
                                                        wagtail.embeds.blocks.EmbedBlock(
                                                            help_text="Youtube url of vimeo url",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Choose an image or paste an embed url",
                                                max_num=1,
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "buttons",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "buttons_align",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-left",
                                                                                "left",
                                                                            ),
                                                                            (
                                                                                "btn-center",
                                                                                "center",
                                                                            ),
                                                                            (
                                                                                "btn-right",
                                                                                "right",
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "buttons",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "button",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "button_style",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                blank=True,
                                                                                                choices=[
                                                                                                    (
                                                                                                        "dark",
                                                                                                        "Default (Dark blue)",
                                                                                                    ),
                                                                                                    (
                                                                                                        "arrow",
                                                                                                        "Dark blue with arrow",
                                                                                                    ),
                                                                                                    (
                                                                                                        "light",
                                                                                                        "light",
                                                                                                    ),
                                                                                                ],
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_link",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "intern",
                                                                                                        main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                            helptext="Choose if you want the button to link to a page internally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "extern",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            helptext="Fill in if the button should link externally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                help_text="Where do you want the button to link to",
                                                                                                max_num=1,
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    required=True,
                                                                                ),
                                                                            )
                                                                        ],
                                                                        help_text="Add a button",
                                                                        min_num=1,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "background",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "color",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "block__bg-white",
                                                                    "White",
                                                                ),
                                                                (
                                                                    "block__bg-gray",
                                                                    "Pale gray",
                                                                ),
                                                                (
                                                                    "block__bg-purple",
                                                                    "Pale purple",
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "size",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "bg__full",
                                                                    "Full backgroundcolor",
                                                                ),
                                                                (
                                                                    "bg__left",
                                                                    "Only backgroundcolor in the left block",
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "grid_layout",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "grid",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("33_66", "33% - 66%"),
                                                                ("50_50", "50% - 50%"),
                                                                ("66_33", "66% - 33%"),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "text",
                                                        main.blocks.rich_text_block.RichtextBlock(),
                                                    ),
                                                    (
                                                        "interactive_input",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "interactive_input",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=main.blocks.storyline_section.get_interactive_inputs
                                                                    ),
                                                                ),
                                                                (
                                                                    "display",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "checkbox_radio",
                                                                                "Show as checkboxe(s) or radiobutton(s)",
                                                                            ),
                                                                            (
                                                                                "button",
                                                                                "Show as button(s)",
                                                                            ),
                                                                        ],
                                                                        help_text="Only applies if the interactive input is a Select type",
                                                                    ),
                                                                ),
                                                                (
                                                                    "visible",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=True,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "locked",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "default_value",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Type the default value exactly as it's shown on the website page",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "static_image",
                                                        main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                block_counts={"static_image": {"max_num": 1}},
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "heroblock",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default color"),
                                                    ("block__bg-gray", "Pale gray"),
                                                    ("block__bg-purple", "Pale purple"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                form_classname="title", required=True
                                            ),
                                        ),
                                        (
                                            "text",
                                            main.blocks.rich_text_block.RichtextBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "media",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "image",
                                                        main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "video",
                                                        wagtail.embeds.blocks.EmbedBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                help_text="Choose an image or paste an embed url",
                                                max_num=1,
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "buttons",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "buttons_align",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-left",
                                                                                "left",
                                                                            ),
                                                                            (
                                                                                "btn-center",
                                                                                "center",
                                                                            ),
                                                                            (
                                                                                "btn-right",
                                                                                "right",
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "buttons",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "button",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "button_style",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                blank=True,
                                                                                                choices=[
                                                                                                    (
                                                                                                        "dark",
                                                                                                        "Default (Dark blue)",
                                                                                                    ),
                                                                                                    (
                                                                                                        "arrow",
                                                                                                        "Dark blue with arrow",
                                                                                                    ),
                                                                                                    (
                                                                                                        "light",
                                                                                                        "light",
                                                                                                    ),
                                                                                                ],
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_link",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "intern",
                                                                                                        main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                            helptext="Choose if you want the button to link to a page internally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "extern",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            helptext="Fill in if the button should link externally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                help_text="Where do you want the button to link to",
                                                                                                max_num=1,
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    required=True,
                                                                                ),
                                                                            )
                                                                        ],
                                                                        help_text="Add a button",
                                                                        min_num=1,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "title_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default color"),
                                                    ("block__bg-gray", "Pale gray"),
                                                    ("block__bg-purple", "Pale purple"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                blank=True,
                                                choices=[
                                                    ("", "Select header size"),
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                ],
                                            ),
                                        ),
                                        (
                                            "text",
                                            main.blocks.rich_text_block.RichtextBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "buttons",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "buttons_align",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-left",
                                                                                "left",
                                                                            ),
                                                                            (
                                                                                "btn-center",
                                                                                "center",
                                                                            ),
                                                                            (
                                                                                "btn-right",
                                                                                "right",
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "buttons",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "button",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "button_style",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                blank=True,
                                                                                                choices=[
                                                                                                    (
                                                                                                        "dark",
                                                                                                        "Default (Dark blue)",
                                                                                                    ),
                                                                                                    (
                                                                                                        "arrow",
                                                                                                        "Dark blue with arrow",
                                                                                                    ),
                                                                                                    (
                                                                                                        "light",
                                                                                                        "light",
                                                                                                    ),
                                                                                                ],
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_link",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "intern",
                                                                                                        main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                            helptext="Choose if you want the button to link to a page internally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "extern",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            helptext="Fill in if the button should link externally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                help_text="Where do you want the button to link to",
                                                                                                max_num=1,
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    required=True,
                                                                                ),
                                                                            )
                                                                        ],
                                                                        help_text="Add a button",
                                                                        min_num=1,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "card_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "image_selector",
                                                            main.blocks.holon_image_chooser.HolonImageChooserBlock(),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=255,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "card_color",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "card__bg-gold",
                                                                        "Gold",
                                                                    ),
                                                                    (
                                                                        "card__bg-blue",
                                                                        "Blue",
                                                                    ),
                                                                    (
                                                                        "card__bg-gray",
                                                                        "Gray",
                                                                    ),
                                                                    (
                                                                        "card__bg-purple",
                                                                        "Purple",
                                                                    ),
                                                                    (
                                                                        "card__bg-pink",
                                                                        "Pink",
                                                                    ),
                                                                    (
                                                                        "card__bg-orange",
                                                                        "Orange",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "item_link",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "intern",
                                                                        main.blocks.page_chooser_block.PageChooserBlock(
                                                                            helptext="Choose if you want the card to link to a page internally",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "extern",
                                                                        wagtail.blocks.URLBlock(
                                                                            helptext="Fill in if the card should link externally",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Optional: add an internal or external link to the card",
                                                                max_num=1,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "buttons",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "buttons_align",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-left",
                                                                                "left",
                                                                            ),
                                                                            (
                                                                                "btn-center",
                                                                                "center",
                                                                            ),
                                                                            (
                                                                                "btn-right",
                                                                                "right",
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "buttons",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "button",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "button_style",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                blank=True,
                                                                                                choices=[
                                                                                                    (
                                                                                                        "dark",
                                                                                                        "Default (Dark blue)",
                                                                                                    ),
                                                                                                    (
                                                                                                        "arrow",
                                                                                                        "Dark blue with arrow",
                                                                                                    ),
                                                                                                    (
                                                                                                        "light",
                                                                                                        "light",
                                                                                                    ),
                                                                                                ],
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "button_link",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "intern",
                                                                                                        main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                            helptext="Choose if you want the button to link to a page internally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "extern",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            helptext="Fill in if the button should link externally",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                help_text="Where do you want the button to link to",
                                                                                                max_num=1,
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    required=True,
                                                                                ),
                                                                            )
                                                                        ],
                                                                        help_text="Add a button",
                                                                        min_num=1,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "information_types",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="main.storylinepageinformationtype"
                    ),
                ),
                (
                    "roles",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="main.storylinepageroletype"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.scenario",
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="customimage.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChallengeMode",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
    ]
