# Generated by Django 4.1.5 on 2023-01-11 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_alter_staticpage_content"),
        ("main", "0029_alter_storylinepageinformationtype_options_and_more"),
    ]

    operations = []
