# Generated by Django 4.1.5 on 2023-01-18 13:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_casusfilter_overviewpage_sandboxpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestPracticeOverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "BestPracticeOverview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.CreateModel(
            name="CasusOverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "CasusOverview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.AddField(
            model_name="overviewpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Introduction of the overview page", null=True
            ),
        ),
        migrations.AlterField(
            model_name="overviewpage",
            name="overview_type",
            field=models.CharField(
                choices=[
                    ("storyline", "Storyline overview"),
                    ("challenge", "Challenge overview"),
                    ("sandbox", "Sandbox overview"),
                ],
                default="storyline",
                help_text="Which type of overview is this page",
                max_length=50,
            ),
        ),
    ]
