# Generated by Django 4.1.5 on 2023-01-16 14:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_casusfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengemodepage",
            name="casus_filter",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.casusfilter"
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="casus_filter",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.casusfilter"
            ),
        ),
    ]
