# Generated by Django 4.1.5 on 2023-01-18 13:46

from django.db import migrations
import main.blocks.holon_image_chooser
import main.blocks.page_chooser_block
import main.blocks.rich_text_block
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_alter_staticpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("block__bg-gray", "Pale gray"),
                                            ("block__bg-purple", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                        ],
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(required=False),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "header_full_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select header size"),
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                        ],
                                    ),
                                ),
                                (
                                    "image_selector",
                                    main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "grid_layout",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "grid",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("33_66", "33% - 66%"),
                                                        ("50_50", "50% - 50%"),
                                                        ("66_33", "66% - 33%"),
                                                    ]
                                                ),
                                            )
                                        ],
                                        required=True,
                                    ),
                                ),
                                (
                                    "column_order",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Default (Text left, Media right)"),
                                            (
                                                "invert",
                                                "Invert columns (Media left, Text right)",
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("block__bg-white", "White"),
                                                        ("block__bg-gray", "Pale gray"),
                                                        (
                                                            "block__bg-purple",
                                                            "Pale purple",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        (
                                                            "bg__full",
                                                            "Full backgroundcolor",
                                                        ),
                                                        (
                                                            "bg__left",
                                                            "Only backgroundcolor in the left block",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(
                                        help_text="Add your text",
                                        required=True,
                                        rows=15,
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    help_text="Youtube url of vimeo url",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "grid_layout",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "grid",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("33_66", "33% - 66%"),
                                                        ("50_50", "50% - 50%"),
                                                        ("66_33", "66% - 33%"),
                                                    ]
                                                ),
                                            )
                                        ],
                                        required=True,
                                    ),
                                ),
                                (
                                    "background",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "color",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("block__bg-white", "White"),
                                                        ("block__bg-gray", "Pale gray"),
                                                        (
                                                            "block__bg-purple",
                                                            "Pale purple",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        (
                                                            "bg__full",
                                                            "Full backgroundcolor",
                                                        ),
                                                        (
                                                            "bg__left",
                                                            "Only backgroundcolor in the left block",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(
                                        help_text="Add your text",
                                        required=True,
                                        rows=15,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "table_block",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            help_text="Add extra columns and rows with right mouse click",
                            required=True,
                            table_options={
                                "editor": "text",
                                "renderer": "text",
                                "startRows": 3,
                            },
                        ),
                    ),
                    (
                        "card_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(required=False),
                                                ),
                                                (
                                                    "image_selector",
                                                    main.blocks.holon_image_chooser.HolonImageChooserBlock(),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255, required=False
                                                    ),
                                                ),
                                                (
                                                    "card_color",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("card__bg-gold", "Gold"),
                                                            ("card__bg-blue", "Blue"),
                                                            ("card__bg-gray", "Gray"),
                                                            (
                                                                "card__bg-purple",
                                                                "Purple",
                                                            ),
                                                            ("card__bg-pink", "Pink"),
                                                            (
                                                                "card__bg-orange",
                                                                "Orange",
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "item_link",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "intern",
                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                    helptext="Choose if you want the card to link to a page internally",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "extern",
                                                                wagtail.blocks.URLBlock(
                                                                    helptext="Fill in if the card should link externally",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Optional: add an internal or external link to the card",
                                                        max_num=1,
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="table",
            field=wagtail.fields.StreamField(
                [
                    (
                        "table_block",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "editor": "text",
                                "renderer": "text",
                                "startRows": 3,
                            }
                        ),
                    )
                ],
                blank=True,
                help_text="Add extra columns and rows with right mouse click",
                null=True,
                use_json_field=True,
            ),
        ),
    ]
