# Generated by Django 4.1.5 on 2023-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_bestpracticeoverviewpage_casusoverviewpage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestpracticeoverviewpage",
            options={"verbose_name": "Best Practice Overview"},
        ),
        migrations.AddField(
            model_name="bestpracticeoverviewpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Introduction of the overview page", null=True
            ),
        ),
        migrations.AddField(
            model_name="casusoverviewpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Introduction of the overview page", null=True
            ),
        ),
    ]
