# Generated by Django 4.1.5 on 2023-01-24 09:24

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_staticpage_content_alter_wikipage_table"),
    ]

    operations = []
