# Generated by Django 4.1.5 on 2023-01-16 14:10

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_challengemodepage_casus_filter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengemodepage",
            name="casus_filter",
        ),
        migrations.RemoveField(
            model_name="storylinepage",
            name="casus_filter",
        ),
        migrations.AddField(
            model_name="casuspage",
            name="casus_filter",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.casusfilter"
            ),
        ),
    ]
