# Generated by Django 4.1.5 on 2023-01-19 12:33

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_staticpage_content_alter_wikipage_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestPracticeOverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Introduction of the overview page",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Best Practice Overview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.CreateModel(
            name="CasusFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("book", "Book"),
                            ("bell", "Bell"),
                            ("cog", "Cog"),
                            ("folder", "Folder"),
                            ("heart", "Heart"),
                            ("info", "Info"),
                            ("lightning", "Lightning bolt"),
                            ("mapmarker", "Map marker"),
                            ("rocket", "Rocket"),
                            ("star", "Star"),
                            ("user", "User"),
                        ],
                        default="green",
                        help_text="Icon shown in storyline overview page",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "CasusFilter",
                "verbose_name_plural": "CasusFilters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CasusOverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Introduction of the overview page",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "CasusOverview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.CreateModel(
            name="InteractiveOverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Introduction of the overview page",
                        null=True,
                    ),
                ),
                (
                    "overview_type",
                    models.CharField(
                        choices=[
                            ("storyline", "Storyline overview"),
                            ("challenge", "Challenge overview"),
                            ("sandbox", "Sandbox overview"),
                        ],
                        default="storyline",
                        help_text="Which type of overview is this page",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Overview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.CreateModel(
            name="SandboxPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sandbox",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.AlterModelOptions(
            name="challengemodepage",
            options={"verbose_name": "Challenge Mode"},
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="table",
            field=wagtail.fields.StreamField(
                [
                    (
                        "table_block",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "editor": "text",
                                "renderer": "text",
                                "startRows": 3,
                            }
                        ),
                    )
                ],
                blank=True,
                help_text="Add extra columns and rows with right mouse click",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="CasusPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "casus_filter",
                    modelcluster.fields.ParentalManyToManyField(to="main.casusfilter"),
                ),
            ],
            options={
                "verbose_name": "CasusPage",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.CreateModel(
            name="BestPracticePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
                (
                    "linked_casusses",
                    models.ManyToManyField(blank=True, to="main.casuspage"),
                ),
            ],
            options={
                "verbose_name": "Best Practice",
                "verbose_name_plural": "Best Practices",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
    ]
