# Generated by Django 4.1.5 on 2023-01-24 09:24

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_staticpage_content_alter_wikipage_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipage",
            name="table",
            field=wagtail.fields.StreamField(
                [
                    (
                        "table_block",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "editor": "text",
                                "renderer": "text",
                                "startRows": 3,
                            }
                        ),
                    )
                ],
                blank=True,
                help_text="Add extra columns and rows with right mouse click",
                null=True,
                use_json_field=None,
            ),
        ),
    ]
