# Generated by Django 4.1.5 on 2023-01-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_bestpracticeoverviewpage_casusfilter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bestpracticeoverviewpage",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="casusoverviewpage",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="interactiveoverviewpage",
            name="introduction",
        ),
    ]
