# Generated by Django 4.1.5 on 2023-01-16 14:13

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_remove_challengemodepage_casus_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casuspage",
            name="casus_filter",
            field=modelcluster.fields.ParentalManyToManyField(to="main.casusfilter"),
        ),
    ]
