# Generated by Django 4.1.5 on 2023-01-26 13:27

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_bestpracticeoverviewpage_bestpracticepage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestpracticepage",
            name="linked_casus",
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to="main.casuspage"),
        ),
        migrations.AddField(
            model_name="casuspage",
            name="linked_best_practices",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="main.bestpracticepage"
            ),
        ),
    ]
