# Generated by Django 4.1.5 on 2023-01-20 09:59

from django.db import migrations
import main.blocks.holon_image_chooser
import main.blocks.page_chooser_block
import main.blocks.rich_text_block
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_remove_bestpracticeoverviewpage_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestpracticeoverviewpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("block__bg-gray", "Pale gray"),
                                            ("block__bg-purple", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Page intro (above the storylines)",
            ),
        ),
        migrations.AddField(
            model_name="casusoverviewpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("block__bg-gray", "Pale gray"),
                                            ("block__bg-purple", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Page intro (above the storylines)",
            ),
        ),
        migrations.AddField(
            model_name="interactiveoverviewpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default color"),
                                            ("block__bg-gray", "Pale gray"),
                                            ("block__bg-purple", "Pale purple"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    main.blocks.rich_text_block.RichtextBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                main.blocks.holon_image_chooser.HolonImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Choose an image or paste an embed url",
                                        max_num=1,
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Fill in this alt-text only when you want to describe the image (for screenreaders and SEO)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "buttons",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "buttons_align",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-left",
                                                                        "left",
                                                                    ),
                                                                    (
                                                                        "btn-center",
                                                                        "center",
                                                                    ),
                                                                    (
                                                                        "btn-right",
                                                                        "right",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "button",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "button_style",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        blank=True,
                                                                                        choices=[
                                                                                            (
                                                                                                "dark",
                                                                                                "Default (Dark blue)",
                                                                                            ),
                                                                                            (
                                                                                                "arrow",
                                                                                                "Dark blue with arrow",
                                                                                            ),
                                                                                            (
                                                                                                "light",
                                                                                                "light",
                                                                                            ),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_text",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "button_link",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "intern",
                                                                                                main.blocks.page_chooser_block.PageChooserBlock(
                                                                                                    helptext="Choose if you want the button to link to a page internally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "extern",
                                                                                                wagtail.blocks.URLBlock(
                                                                                                    helptext="Fill in if the button should link externally",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Where do you want the button to link to",
                                                                                        max_num=1,
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            required=True,
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="Add a button",
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Page intro (above the storylines)",
            ),
        ),
    ]
