# Generated by Django 4.1.5 on 2023-01-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0003_alter_customimage_file_hash"),
        ("main", "0035_bestpracticepage_linked_casus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestpracticepage",
            name="card_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card__bg-gold", "Gold"),
                    ("card__bg-blue", "Blue"),
                    ("card__bg-gray", "Gray"),
                    ("card__bg-purple", "Purple"),
                    ("card__bg-pink", "Pink"),
                    ("card__bg-orange", "Orange"),
                ],
                default="card__bg-blue",
                help_text="Background color in the overview pages",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bestpracticepage",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the casus", null=True),
        ),
        migrations.AddField(
            model_name="bestpracticepage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customimage.customimage",
            ),
        ),
    ]
