# Generated by Django 4.1.5 on 2023-01-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_wikipage_table"),
        ("main", "0035_alter_staticpage_content_alter_wikipage_content"),
    ]

    operations = []
