# Generated by Django 4.1.5 on 2023-01-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_bestpracticeoverviewpage_bestpracticepage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casuspage",
            name="casus_filter",
        ),
        migrations.AddField(
            model_name="casuspage",
            name="casus_filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="main.casusfilter",
            ),
        ),
    ]
