# Generated by Django 4.1.5 on 2023-02-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_remove_casuspage_casus_filter_casuspage_casus_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casuspage",
            name="casus_filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.casusfilter",
            ),
        ),
    ]
