# Generated by Django 4.1.5 on 2023-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_bestpracticepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="casuspage",
            name="best_practice",
            field=models.ManyToManyField(blank=True, to="main.bestpracticepage"),
        ),
    ]
