# Generated by Django 4.1.5 on 2023-01-17 09:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_casuspage_best_practice"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverviewPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overview",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "main.basepage",
            ),
        ),
        migrations.AlterModelOptions(
            name="bestpracticepage",
            options={
                "verbose_name": "Best Practice",
                "verbose_name_plural": "Best Practices",
            },
        ),
        migrations.AlterModelOptions(
            name="challengemodepage",
            options={"verbose_name": "Challenge Mode"},
        ),
    ]
