# Generated by Django 4.1.6 on 2023-02-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_challengemodepage_feedbackmodals"),
        ("main", "0037_bestpracticeoverviewpage_bestpracticepage_and_more"),
    ]

    operations = []
