# Generated by Django 4.1.5 on 2023-01-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_overviewpage_alter_bestpracticepage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overviewpage",
            name="overview_type",
            field=models.CharField(
                choices=[
                    ("storyline", "Storyline overview"),
                    ("challenge", "Challenge overview"),
                    ("sandbox", "Sandbox overview"),
                    ("casus", "Casus overview"),
                    ("bestpractice", "Best Practice overview"),
                ],
                default="storyline",
                help_text="Which type of overview is this page",
                max_length=50,
            ),
        ),
    ]
