# Generated by Django 4.1.5 on 2023-01-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_sandboxpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CasusOverviewPage",
        ),
    ]
