# Generated by Django 4.1.7 on 2023-02-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_alter_challengemodepage_storyline_and_more"),
        ("main", "0040_alter_challengemodepage_feedbackmodals"),
    ]

    operations = []
