# Generated by Django 4.1.7 on 2023-02-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_graphcolors"),
        ("main", "0044_merge_20230220_0856"),
    ]

    operations = []
