# Generated by Django 4.1.7 on 2023-02-24 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_graphcolors"),
        ("main", "0045_alter_challengemodepage_storyline_and_more"),
    ]

    operations = []
