# Generated by Django 4.1.6 on 2023-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_challengemodepage_storyline_and_more"),
        ("main", "0047_alter_challengemodepage_feedbackmodals_and_more"),
    ]

    operations = []
