# Generated by Django 4.1.7 on 2023-03-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_casuspage_scenario_alter_challengemodepage_storyline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengemodepage",
            name="scenario",
        ),
        migrations.RemoveField(
            model_name="storylinepage",
            name="scenario",
        ),
        migrations.AlterField(
            model_name="casuspage",
            name="scenario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="holon.scenario",
            ),
        ),
    ]
