# Generated by Django 4.1.7 on 2023-03-16 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0048_alter_challengemodepage_feedbackmodals"),
        ("main", "0050_alter_challengemodepage_feedbackmodals_and_more"),
    ]

    operations = []
