# Generated by Django 4.1.7 on 2023-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_interactiveelementunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveelementunit",
            name="name",
            field=models.CharField(default="percentage", max_length=50),
        ),
        migrations.AlterField(
            model_name="interactiveelementunit",
            name="symbol",
            field=models.CharField(default="%", max_length=10),
        ),
    ]
