# Generated by Django 4.1.7 on 2023-03-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0054_alter_interactiveelementunit_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactiveelementunit",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="interactiveelementunit",
            name="symbol",
            field=models.CharField(max_length=10),
        ),
    ]
