# Generated by Django 4.1.7 on 2023-03-30 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0054_alter_challengemodepage_storyline_and_more"),
        ("main", "0055_alter_interactiveelementunit_name_and_more"),
    ]

    operations = []
