# Generated by Django 4.1.7 on 2023-04-12 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0056_alter_challengemodepage_storyline_and_more"),
        ("main", "0056_merge_20230330_1353"),
    ]

    operations = []
