# Generated by Django 4.1.7 on 2023-04-12 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_merge_20230412_0948"),
        ("main", "0058_alter_challengemodepage_feedbackmodals_and_more"),
    ]

    operations = []
