# Generated by Django 4.1.7 on 2023-04-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0058_alter_challengemodepage_storyline_and_more"),
        ("main", "0060_alter_challengemodepage_storyline_and_more"),
    ]

    operations = []
