# Generated by Django 4.1.9 on 2023-06-29 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0067_sandboxpage_card_color_sandboxpage_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casuspage",
            name="casus_filter",
        ),
        migrations.DeleteModel(
            name="CasusFilter",
        ),
    ]
