# Generated by Django 4.1.9 on 2023-06-29 13:13

from django.db import migrations
import main.blocks.page_chooser_block
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_sandboxpage_card_color_sandboxpage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengemodepage",
            name="wiki_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cost_benefit",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from cost benefit page",
                            required=False,
                        ),
                    ),
                    (
                        "holarchy",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from holarchy page",
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="sandboxpage",
            name="wiki_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cost_benefit",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from cost benefit page",
                            required=False,
                        ),
                    ),
                    (
                        "holarchy",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from holarchy page",
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="storylinepage",
            name="wiki_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cost_benefit",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from cost benefit page",
                            required=False,
                        ),
                    ),
                    (
                        "holarchy",
                        main.blocks.page_chooser_block.PageChooserBlock(
                            "main.WikiPage",
                            helptext="Link to wiki from holarchy page",
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
