# Generated by Django 4.1.9 on 2023-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0068_challengemodepage_wiki_links_sandboxpage_wiki_links_and_more"),
        ("main", "0068_remove_casuspage_casus_filter_delete_casusfilter"),
    ]

    operations = []
