export default function handler(req, res) {
    const data = {
        Huishouden: {
          Afschrijving: "-60",
          Huishouden: null,
          "Commercieel bedrijf": "0",
          Overheidsinstelling: "0",
          Energieleverancier: "-200",
          Netbeheerder: "-200",
          Overheid: "125",
          "Netto kosten": "-335",
        },
        "Commercieel bedrijf": {
          Afschrijving: "0",
          Huishouden: "0",
          "Commercieel bedrijf": null,
          Overheidsinstelling: "0",
          Energieleverancier: "-200",
          Netbeheerder: "-100",
          Overheid: "-50",
          "Netto kosten": "-350",
        },
        Overheidsinstelling: {
          Afschrijving: "-20",
          Huishouden: "0",
          "Commercieel bedrijf": "0",
          Overheidsinstelling: null,
          Energieleverancier: "-100",
          Netbeheerder: "-200",
          Overheid: "-75",
          "Netto kosten": "-395",
        },
        Energieleverancier: {
          Afschrijving: "0",
          Huishouden: "200",
          "Commercieel bedrijf": "200",
          Overheidsinstelling: "100",
          Energieleverancier: null,
          Netbeheerder: "0",
          Overheid: "0",
          "Netto kosten": "500",
        },
        Netbeheerder: {
          Afschrijving: "-500",
          Huishouden: "200",
          "Commercieel bedrijf": "100",
          Overheidsinstelling: "200",
          Energieleverancier: "0",
          Netbeheerder: null,
          Overheid: "0",
          "Netto kosten": "0",
        },
        Overheid: {
          Afschrijving: "0",
          Huishouden: "-125",
          "Commercieel bedrijf": "50",
          Overheidsinstelling: "75",
          Energieleverancier: "0",
          Netbeheerder: "0",
          Overheid: null,
          "Netto kosten": "0",
        },
        Testlabel: {
            Afschrijving: "0",
            Huishouden: "-125",
            "Commercieel bedrijf": "50",
            Overheidsinstelling: "75",
            Energieleverancier: "0",
            Netbeheerder: "0",
            Overheid: null,
            "Netto kosten": "0",
            },
          "Nog een test": {
            Afschrijving: "0",
            Huishouden: "-125",
            "Commercieel bedrijf": "50",
            Overheidsinstelling: "75",
            Energieleverancier: "0",
            Netbeheerder: "0",
            Overheid: null,
            "Netto kosten": "0",
          },
          "Eena laatste": {
            Afschrijving: "0",
            Huishouden: "-125",
            "Commercieel bedrijf": "50",
            Overheidsinstelling: "75",
            Energieleverancier: "0",
            Netbeheerder: "0",
            Overheid: null,
            "Netto kosten": "0",
          },
          "Laatste": {
            Afschrijving: "0",
            Huishouden: "-125",
            "Commercieel bedrijf": "50",
            Overheidsinstelling: "75",
            Energieleverancier: "0",
            Netbeheerder: "0",
            Overheid: null,
            "Netto kosten": "0",
          },
      };

    res.status(200).json(data);
  }
  